apps/mactor/urls.py
from django.conf.urls import url
from django.contrib.auth.decorators import login_required
from .views import CrearEstudio, ConsultarEstudio, EditarEstudio, EliminarEstudio, \
    ListaActores, CrearActor, EditarActor, EliminarActor, consultar_actor, importar_actores_fichas, \
    ListaFichas, CrearFicha, EditarFicha, EliminarFicha, ConsultarFicha, \
    ListaObjetivos, CrearObjetivo, EditarObjetivo, EliminarObjetivo, consultar_objetivo, importar_objetivos, \
    ListaInfluenciasMID, CrearInfluenciaMID, EditarInfluenciaMID, ConsultarInfluenciaMID, \
    generar_matriz_mid, generar_matriz_midi, generar_matriz_maxima, generar_matriz_ri, \
    generar_matriz_balance, generar_indicador_estabilidad,\
    ListaRelacionesMAO, CrearRelacionMAO, EditarRelacionMAO, \
    ConsultarRelacionMAO, generar_matriz_mao, generar_matrices_caa_daa, generar_lista_descendiente,\
    consultar_actores_faltantes, \
    EditarInformeFinal, exportar_estudio_xls, \
    histograma_mid, datos_histograma_mid, histograma_ri, datos_histograma_ri, \
    histograma_implicacion, histograma_movilizacion, datos_histogramas_mao,  \
    datos_histograma_caa_daa, histograma_caa_daa, \
    generar_mapa_midi, datos_mapa_midi, generar_mapa_caa_daa, datos_mapa_caa_daa, \
    generar_grafo_caa, datos_grafo_caa, generar_grafo_daa, datos_grafo_daa, \
    activar_consenso_mid, activar_consenso_mao, activar_consenso_caa_daa

urlpatterns = [

    # Urls modelo Estudio_mactor

    url(r'^agregar_estudio/(?P<pk>\d+)/$', login_required(CrearEstudio.as_view()), name='nuevo_estudio'),
    url(r'^consultar_estudio/(?P<pk>\d+)/$', login_required(ConsultarEstudio.as_view()), name='consultar_estudio'),
    url(r'^editar_estudio/(?P<pk>\d+)/$', login_required(EditarEstudio.as_view()), name='editar_estudio'),
    url(r'^eliminar_estudio/(?P<pk>\d+)/$', login_required(EliminarEstudio.as_view()), name='eliminar_estudio'),

    # Urls modelo Actor
    url(r'^actores/(\d+)/$', login_required(ListaActores.as_view()), name='actores'),
    url(r'^nuevo_actor/(\d+)/$', login_required(CrearActor.as_view()), name='nuevo_actor'),
    url(r'^editar_actor/(?P<pk>\d+)/$', login_required(EditarActor.as_view()), name='editar_actor'),
    url(r'^eliminar_actor/(?P<pk>\d+)/$', login_required(EliminarActor.as_view()), name='eliminar_actor'),
    url(r'consultar_actor', login_required(consultar_actor)),
    url(r'importar_actores_fichas', login_required(importar_actores_fichas)),

    # Urls modelo Ficha
    url(r'^fichas/(\d+)/$', login_required(ListaFichas.as_view()), name='fichas'),
    url(r'^nueva_ficha/(\d+)/$', login_required(CrearFicha.as_view()), name='nueva_ficha'),
    url(r'^editar_ficha/(?P<pk>\d+)/$', login_required(EditarFicha.as_view()), name='editar_ficha'),
    url(r'^consultar_ficha/(?P<pk>\d+)/$', login_required(ConsultarFicha.as_view()), name='consultar_ficha'),
    url(r'^eliminar_ficha/(?P<pk>\d+)/$', login_required(EliminarFicha.as_view()), name='eliminar_ficha'),

    # Urls modelo Objetivo
    url(r'^objetivos/(\d+)/$', login_required(ListaObjetivos.as_view()), name='objetivos'),
    url(r'^nuevo_objetivo/(\d+)/$', login_required(CrearObjetivo.as_view()), name='nuevo_objetivo'),
    url(r'^editar_objetivo/(?P<pk>\d+)/$', login_required(EditarObjetivo.as_view()), name='editar_objetivo'),
    url(r'^eliminar_objetivo/(?P<pk>\d+)/$', login_required(EliminarObjetivo.as_view()), name='eliminar_objetivo'),
    url(r'consultar_objetivo', login_required(consultar_objetivo)),
    url(r'importar_objetivos', login_required(importar_objetivos)),

    # Urls modelo RelacionMID
    url(r'^influenciasMID/(\d+)/$', login_required(ListaInfluenciasMID.as_view()), name='influenciasMID'),
    url(r'^nueva_influencia/(?P<actorY>\d+)/(?P<actorX>\d+)/$', login_required(CrearInfluenciaMID.as_view()),
        name='nueva_mid_matriz'),
    url(r'^consultar_mid/(?P<pk>\d+)/(?P<tipoAcceso>\w+)/$', login_required(ConsultarInfluenciaMID.as_view()),
        name='consultar_mid'),
    url(r'^editar_mid/(?P<pk>\d+)/(?P<tipoAcceso>\w+)/$', login_required(EditarInfluenciaMID.as_view()),
        name='editar_mid'),
    url(r'^matriz_mid/(?P<idEstudio>\d+)/$', login_required(generar_matriz_mid), name='matriz_mid'),
    url(r'^matriz_midi/(?P<idEstudio>\d+)/$', login_required(generar_matriz_midi), name='matriz_midi'),
    url(r'^matriz_maxima/(?P<idEstudio>\d+)/$', login_required(generar_matriz_maxima), name='matriz_maxima'),
    url(r'^matriz_ri/(?P<idEstudio>\d+)/$', login_required(generar_matriz_ri), name='matriz_ri'),
    url(r'^matriz_balance/(?P<idEstudio>\d+)/$', login_required(generar_matriz_balance), name='matriz_balance'),
    url(r'^estabilidad/(?P<idEstudio>\d+)/$', login_required(generar_indicador_estabilidad), name='estabilidad'),

    # Urls modelo RelacionMAO
    url(r'^relacionesMAO/(\d+)/$', login_required(ListaRelacionesMAO.as_view()), name='relacionesMAO'),
    url(r'^nueva_MAO/(?P<actor>\d+)/(?P<objetivo>\d+)/$', login_required(CrearRelacionMAO.as_view()),
        name='nueva_MAO'),
    url(r'^consultar_mao/(?P<pk>\d+)/(?P<tipoAcceso>\w+)/$', login_required(ConsultarRelacionMAO.as_view()),
        name='consultar_mao'),
    url(r'^editar_mao/(?P<pk>\d+)/(?P<tipoAcceso>\w+)/$', login_required(EditarRelacionMAO.as_view()),
        name='editar_mao'),
    url(r'^matriz_mao/(?P<idEstudio>\d+)/(?P<numero_matriz>\d)/', login_required(generar_matriz_mao),
        name='matriz_mao'),
    url(r'^matriz_caa_daa/(?P<idEstudio>\d+)/(?P<numero_matriz>\d)/$', login_required(generar_matrices_caa_daa),
        name='caa_daa'),
    url(r'^lista_descendientes/(?P<idEstudio>\d+)/(?P<numero_matriz>\d)/$', login_required(generar_lista_descendiente),
        name='descendientes'),

    # Urls modelo informe final
    url(r'^editar_informe/(?P<pk>\d+)/$', login_required(EditarInformeFinal.as_view()), name='editar_informe'),

    # Urls consultas ajax
    url(r'ficha-ajax/$', login_required(consultar_actores_faltantes)), # obtiene lista actores X registrados en la ficha

    # Urls consensos
    url(r'^consenso_mid/(?P<idEstudio>\d+)/(?P<matriz>\d)', login_required(activar_consenso_mid), name='consenso_mid'),
    url(r'^consenso_mao/(?P<idEstudio>\d+)/(?P<matriz>\d)/(?P<tipo>\d)', login_required(activar_consenso_mao),
        name='consenso_mao'),
    url(r'^consenso_caa_daa/(?P<idEstudio>\d+)/(?P<matriz>\d)/(?P<tipo>\d)', login_required(activar_consenso_caa_daa),
        name='consenso_caa_daa'),

    # Urls histogramas mid
    url(r'^histograma_mid/(?P<idEstudio>\d+)/$', login_required(histograma_mid), name='histograma_mid'),
    url(r'datos_histograma_mid', login_required(datos_histograma_mid)),
    url(r'^histograma_ri/(?P<idEstudio>\d+)/$', login_required(histograma_ri), name='histograma_ri'),
    url(r'datos_histograma_ri', login_required(datos_histograma_ri)),

    # Urls histogramas mao
    url(r'^histograma_implicacion/(?P<idEstudio>\d+)/(?P<numero_matriz>\d)/$', login_required(histograma_implicacion),
        name='implicacion'),
    url(r'^histograma_movilizacion/(?P<idEstudio>\d+)/(?P<numero_matriz>\d)/$', login_required(histograma_movilizacion),
        name='movilizacion'),
    url(r'datos_histograma', login_required(datos_histogramas_mao)),

    # Urls mapa actores
    url(r'^mapa_actores/(?P<idEstudio>\d+)/$', login_required(generar_mapa_midi), name='mapa_actores'),
    url(r'datos_plano_midi', login_required(datos_mapa_midi)),

    # Urls graficos caa y daa
    url(r'^mapa_caa_daa/(?P<idEstudio>\d+)/(?P<numero_matriz>\d)/$', login_required(generar_mapa_caa_daa),
        name='mapa_caa_daa'),
    url(r'datos_mapa_caa_daa', login_required(datos_mapa_caa_daa)),
    url(r'^histograma_caa_daa/(?P<idEstudio>\d+)/(?P<numero_matriz>\d)/$', login_required(histograma_caa_daa),
        name='hist_caa_daa'),
    url(r'datos_caa_daa', login_required(datos_histograma_caa_daa)),
    url(r'^grafo_caa/(?P<idEstudio>\d+)/(?P<numero_matriz>\d)$', login_required(generar_grafo_caa), name='grafo_caa'),
    url(r'datos_grafo_caa', login_required(datos_grafo_caa)),
    url(r'^grafo_daa/(?P<idEstudio>\d+)/(?P<numero_matriz>\d)$', login_required(generar_grafo_daa), name='grafo_daa'),
    url(r'datos_grafo_daa', login_required(datos_grafo_daa)),

    # Urls exportar a excel
    url(r'exportar_estudios/xls/(?P<idEstudio>\d+)/$', login_required(exportar_estudio_xls), name='exportar_excel'),

]

apps/usuario/urls.py
from django.conf.urls import url
from django.contrib.auth.decorators import login_required
from .views import RegistrarUsuarioProyecto, RegistrarUsuarioEstudio

urlpatterns = [
    # si id = 0, se esta agregando un usuario desde la vista de creacion
    # si id != 0 se esta agregando un usuario desde la vista de edicion
    url(r'^registrar_usuario_proyecto/(?P<id>\d+)/$', login_required(RegistrarUsuarioProyecto.as_view()), name='registrar_usuario_proyecto'),
    url(r'^registrar_usuario_estudio/(?P<idProyecto>\d+)/(?P<tipoEstudio>\d+)/(?P<idEstudio>\d+)/$', login_required(RegistrarUsuarioEstudio.as_view()), name='registrar_usuario_estudio'),
    ]

softprosp/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from apps.usuario.views import UserRegistrationView

urlpatterns = [
  url(r'^admin/', admin.site.urls),
  # sobreescritura del formulario de registro de registration-redux
  url(r'^accounts/register/$', UserRegistrationView.as_view(),
      name='registration_register'),
  url(r'^proyecto/', include('apps.proyecto.urls', namespace="proyecto")),
  url(r'^usuario/', include('apps.usuario.urls', namespace="usuario")),
  url(r'^abaco/', include('apps.abaco.urls', namespace="abaco")),
  url(r'^delphi/', include('apps.delphi.urls', namespace="delphi")),
  url(r'^entrevista/', include('apps.entrevista.urls', namespace="entrevista")),
  url(r'^brainstorming/',
      include('apps.brainstorming.urls', namespace="brainstorming")),
  url(r'^mactor/', include('apps.mactor.urls', namespace="mactor")),
  url(r'^multipol/', include('apps.multipolv1.urls', namespace='multipol')),
  url(r'^extrapolacion', include('apps.extrapolacion_tendencias.urls',
                                 namespace='extrapolacion')),
  # urls vista control de usuarios paquete Registration redux
  url(r'^accounts/', include('registration.backends.default.urls')),
]

apps/mactor/models.py
from django.db import models
from ..proyecto.models import Proyecto, Tecnica
from django.contrib.auth.models import User
from django.utils.timezone import now
from django.core.urlresolvers import reverse

"""MODELO ESTUDIO MACTOR--------------------------------------------------------------------------------------------"""


class EstudioMactor(models.Model):

    tipoTecnica = models.ForeignKey(Tecnica, null=True) # el tipo se agrega mandando e objeto por contexto
    titulo = models.CharField(max_length=200)
    descripcion = models.TextField()
    idAdministrador = models.ForeignKey(User, verbose_name='administrador', related_name='mactor_administrador')
    idCoordinador = models.ForeignKey(User, verbose_name='coordinador', related_name='mactor_coordinador')
    idExpertos = models.ManyToManyField(User, verbose_name='Expertos', related_name='mactor_expertos_set')
    fecha_inicio = models.DateField(default=now)
    fecha_final = models.DateField(default=now)
    dias_finalizacion_informe = models.PositiveIntegerField(default=5)
    estado = models.BooleanField(default=True)
    idProyecto = models.ForeignKey(Proyecto, null=True, on_delete=models.CASCADE)

# Definicion de nombre singular y plural del modelo
    class Meta:
        verbose_name = 'Estudio Mactor'
        verbose_name_plural = 'Estudios Mactor'
        unique_together = [('titulo', 'tipoTecnica', 'idProyecto')]

    def get_absolute_url(self):
        return reverse('proyecto:ver_estudios_proyecto', args={self.idProyecto.id})

# Campo a mostrar del modelo Estudio_Mactor (tabla en admin y listas desplegables)
    def __str__(self):
        return u'{0}'.format(self.titulo)


"""MODELO ACTOR-----------------------------------------------------------------------------------------------------"""


class Actor(models.Model):

    nombreLargo = models.CharField(max_length=100)
    nombreCorto = models.CharField(max_length=5)
    descripcion = models.TextField(max_length=200, null=True, blank=True)
    idEstudio = models.ForeignKey(EstudioMactor, default=0, on_delete=models.CASCADE)

    class Meta:
        verbose_name = 'Actor'
        verbose_name_plural = 'Actores'
        unique_together = [('nombreLargo', 'nombreCorto', 'idEstudio'),
                           ('nombreLargo', 'idEstudio'),
                           ('nombreCorto', 'idEstudio')]

    def get_absolute_url(self):
        return reverse('mactor:actores', args={self.idEstudio.id})

    def __str__(self):
        return u'{0} - {1}'.format(self.nombreCorto, self.nombreLargo)


"""MODELO FICHA DE ESTRATEGIAS--------------------------------------------------------------------------------------"""


class Ficha(models.Model):

    idActorY = models.ForeignKey(Actor, default=0, related_name='mactor_actorY_ficha', on_delete=models.CASCADE)
    idActorX = models.ForeignKey(Actor, default=0, related_name='mactor_actorX_ficha', on_delete=models.CASCADE)
    estrategia = models.TextField(default="", blank=False)

    class Meta:
        verbose_name = 'Ficha de estrategias'
        verbose_name_plural = 'Fichas de estrategia'
        unique_together = ('idActorY', 'idActorX')

    def __str__(self):
        return u'{0} - {1} - {2}'.format(self.idActorX, self.idActorY, self.estrategia)


"""MODELO OBJETIVO--------------------------------------------------------------------------------------------------"""


class Objetivo(models.Model):

    nombreLargo = models.CharField(max_length=100)
    nombreCorto = models.CharField(max_length=5)
    descripcion = models.TextField(max_length=500, null=True, blank=True)
    idEstudio = models.ForeignKey(EstudioMactor, default=0, on_delete=models.CASCADE)

    class Meta:
        verbose_name = 'Objetivo'
        verbose_name_plural = 'Objetivos'
        unique_together = [('nombreLargo', 'nombreCorto', 'idEstudio'),
                           ('nombreLargo', 'idEstudio'),
                           ('nombreCorto', 'idEstudio')]

    def get_absolute_url(self):
        return reverse('mactor:objetivos', args={self.idEstudio.id})

    def __str__(self):
        return u'{0} - {1}'.format(self.nombreCorto, self.nombreLargo)


"""MODELO RELACIONES DE INFLUENCIA DIRECTA---------------------------------------------------------------------------"""


class RelacionMID(models.Model):

    idActorX = models.ForeignKey(Actor, default=0, related_name='mactor_actorX_set', on_delete=models.CASCADE)
    idActorY = models.ForeignKey(Actor, default=0, blank=False, related_name='mactor_actorY_set', on_delete=models.CASCADE)
    valor = models.IntegerField()
    justificacion = models.TextField(default="Justificación de la relación entre los actores")
    idExperto = models.ForeignKey(User, null=True)

    class Meta:
        verbose_name = 'Relacion de Influencia'
        verbose_name_plural = 'Relaciones de influencia'
        unique_together = ('idActorX', 'idActorY', 'idExperto')

    def __str__(self):
        return u'{0} - {1} - {2}'.format(self.idActorY, self.idActorX, self.valor)


"""MODELO RELACIONES DE ACTOR x OBJETIVO---------------------------------------------------------------------------"""


class RelacionMAO(models.Model):

    tipo = models.IntegerField(null=True, blank=True)
    idActorY = models.ForeignKey(Actor, default=0, on_delete=models.CASCADE)
    idObjetivoX = models.ForeignKey(Objetivo, default=0, on_delete=models.CASCADE)
    valor = models.IntegerField()
    justificacion = models.TextField(default="Justificación de la relación entre el actor y el objetivo")
    idExperto = models.ForeignKey(User, null=True)

    class Meta:
        verbose_name = 'Relacion MAO'
        verbose_name_plural = 'Relaciones MAO'
        unique_together = ('tipo', 'idActorY', 'idObjetivoX', 'idExperto')

    def __str__(self):
        return u'{0} - {1} - {2} - {3} - {4}'.format(self.tipo, self.idActorY, self.idObjetivoX, self.valor, self.idExperto)


"""MODELO INFORME FINAL---------------------------------------------------------------------------------------------"""


class InformeFinal(models.Model):

    fecha = models.DateTimeField(auto_now=True)
    informe = models.TextField()
    estado = models.BooleanField(default=False)
    idEstudio = models.ForeignKey(EstudioMactor, default=0, on_delete=models.CASCADE)

    class Meta:
        verbose_name = 'Informe final'
        verbose_name_plural = 'Informes finales'

    def __str__(self):
        return u'{0} - {1} - {2}'.format(self.idEstudio, self.fecha, self.informe, self.estado)


# Sobreescritura del modelo usuario


def get_name(self):
    if self.first_name != '':
        return '{} {}'.format(self.first_name, self.last_name)
    else:
        return '{}'.format(self.username)

User.add_to_class("__str__", get_name)

templates/mactor/estudio/crear_estudio_mactor.html
{% extends 'base.html' %}
{% load staticfiles %}
{% load crispy_forms_tags %}

{% block extra_css %}
    <!-- Select2 -->
    <link rel="stylesheet" href="{% static 'css/select2/css/select2.min.css' %}">
    <!-- DataPicker -->
    <link rel="stylesheet" href="{% static 'css/bootstrap-datepicker.min.css' %}">

    <style>
        #expertos li { color: black }
    </style>
{% endblock %}

{% block content %}
    {% if request.user == proyecto.idAdministrador and proyecto.estado %}
        <div class="matter">
            <div class="container">
                <div class="row">
                    <div class="col-md-12">
                            <div class="widget-head">
                                <div class="box-header with-border">
                                  <h3 class="box-title">Nuevo estudio MACTOR</h3>
                                </div>
                            </div>
                            <div class="widget-content">
                                <div class="padd">

                                    {% include 'messages.html' %}

										<!-- Form starts.  -->
                                    <form class="form-horizontal" role="form" method="post">
                                        {% csrf_token %}

                                       <div class="row hidden">
                                            <div class="col-md-8 col-md-offset-1">
                                                <label class="control-label" style="text-align: left">Tecnica</label>
                                                <input class="form-control" type="text" value="{{tecnica}}" name="tipoTecnica">
                                            </div>
                                        </div>

                                        <div class="row">
                                            <div class="col-md-8 col-md-offset-1">
                                                {{ form.titulo|as_crispy_field }}
                                            </div>
                                        </div>

                                        <div class="row">
                                            <div class="col-md-8 col-md-offset-1">
                                                {{ form.descripcion|as_crispy_field }}
                                            </div>
                                        </div>

                                        <div class="row">
                                            <div class="col-md-8 col-md-offset-1">
                                                <div class="form-group">
                                                        <label class="control-label" style="text-align: left">Coordinador*</label>
                                                        <select name="idCoordinador" class="form-control select2" required id="id_idCoordinador">
                                                            <option value="" selected>----Seleccionar----</option>
                                                            {% for coo in proyecto.idCoordinadores.all %}
                                                                <option value="{{coo.id}}">{{ coo }}</option>
                                                            {% endfor %}
                                                        </select>
                                                    </div>
                                            </div>
                                        </div>

                                        <div class="row" id="expertos">
                                            <div class="col-md-8 col-md-offset-1">
                                                {{form.idExpertos|as_crispy_field}}
                                            </div>
                                        </div>

                                        <div class="row">
                                            <div class="col-md-8 col-md-offset-1">
                                                {{form.fecha_inicio|as_crispy_field}}
                                            </div>

                                            <div class="col-md-8 col-md-offset-1">
                                                <span style="color: red">Nota: Tenga en cuenta que la fecha final no puede ser posterior a la fecha de cierre del proyecto ({{ proyecto.fecha_final }}). </span>
                                                <br>
                                                {{form.fecha_final|as_crispy_field}}
                                            </div>

                                            <div class="col-md-8 col-md-offset-1">
                                               {{ form.dias_finalizacion_informe|as_crispy_field }}
                                            </div>
                                        </div>

                                        <div class="row">
                                           <div class="col-md-8 col-md-offset-1">
                                               <span style="color: red">Nota: Al cumplirse la fecha de cierre del estudio, el estado de este cambiará automáticamente a cerrado. </span>
                                               <br>
                                               {{ form.estado|as_crispy_field }}
                                            </div>

                                            <div class="col-md-8 col-md-offset-1 hidden">
                                                <input class="form-control" type="text" value="{{proyecto.id}}" name="idProyecto">
                                            </div>
                                        </div>

                                        <br>
                                        <div class="form-group">
                                            <div class="col-md-8 col-md-offset-3">
                                                <a class="btn btn-success" href="{% url 'proyecto:ver_estudios_proyecto' proyecto.id %}" title="Estudios del proyecto"><i class="fa fa-arrow-left"></i> Atrás</a>
                                                <a class="btn btn-primary" href="{% url 'usuario:registrar_usuario_estudio' proyecto.id 1 0 %}" title="Registrar nuevo usuario"><i class="fa fa-plus"></i> Usuario</a>
                                                <a class="btn btn-primary" data-toggle="modal" href="#myModal" title="Ayuda"><i class="fa fa-book"></i> Ayuda</a>
                                                <button type="submit" class="btn btn-primary" title="Guardar"><i class="fa fa-save"></i> Guardar</button>
                                            </div>
                                        </div>
                                    </form>

                                </div>
                            </div>

        <!--INICIO MODAL AYUDA------------------------- -->

		<div id="myModal" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
				  <div class="modal-dialog">
					  <div class="modal-content">
						  <div class="modal-header">
							  <button type="button" class="close" data-dismiss="modal" aria-hidden="true">X</button>
							  <h4 class="modal-title">Ayuda - Nuevo estudio MACTOR</h4>
						  </div>
						  <div class="modal-body" style="text-align: justify">
							  <p>Ingrese la información básica del estudio, tenga en cuenta los roles que pueden ser ejercidos
                                  dentro del mismo:
								  <br>
								  <br>
								  <i class="fa fa-user"></i> Administrador: encargado de crear y finalizar el estudio. También
                                  puede llevar a cabo las tareas del coordinador.
								  <br>
								  <br>
								  <i class="fa fa-user"></i> Coordinador: responsable de registrar las entradas necesarias
                                  para el desarrollo del estudio (actores, estrategias y objetivos) y redactar el informe final
                                  de acuerdo al consenso entre los expertos.
								  <br>
								  <br>
								  <i class="fa fa-users"></i> Experto: encargado de diligenciar las matrices necesarias para
                                el análisis de las convergencias y divergencias entre los actores respecto a los objetivos
                                estudiados.
								  <br>
								  <br>
								  <p style="color: black">Nota 1: El administrador puede ocupar dentro de un estudio los tres roles descritos, asi como
                                el coordinador designado puede hacer parte del grupo de expertos.</p>
                                <p style="color: black">Nota 2: Una vez finalizado el estudio el coordinador cuenta con la cantidad de dias registrados al
                                    crear el estudio para redactar el informe, este informe puede ser modificado siempre que el estado del
                                    mismo sea "Abierto". Usted como administrador cuenta con el permiso de redactar, modificar y cerrar el informe
                                    si asi lo desea. </p>

							  </p>
						  </div>
						  <div class="modal-footer">
							  <button type="button" class="btn btn-default" data-dismiss="modal" aria-hidden="true">Cerrar</button>
						  </div>
					  </div>
				  </div>
			  </div>

                    </div>
                </div>
            </div>
</div>
    {% else %}
        <h2>No cuenta con permisos para acceder a esta página.</h2>
    {% endif %}

{% endblock %}

{% block extra_js %}
    <!-- Select2 -->
    <script src="{% static 'js/select2/js/select2.full.min.js' %}"></script>
    <!-- Datapicker -->
    <script src="{% static 'js/moment.min.js' %}"></script>
    <script src="{% static 'js/bootstrap-datepicker.min.js' %}"></script>
    <script src="{% static 'js/mactor/controlFechas.js' %}"></script>

    <script>
        $(function ()
        {
            //Initialize Select2 Elements
            $('.select2').select2()
        })
    </script>
{% endblock %}

templates/mactor/estudio/select_datos_estudio.html
<!--Opciones que dan acceso a los diferentes datos del estudio mactor-->

<select style="float: right" onchange="location = this.value;">
    <option value="">Opciones</option>
    <option value="{% url 'proyecto:ver_estudios_proyecto' estudio.idProyecto_id %}">Estudios del proyecto</option>
    <option value="{% url 'proyecto:ver_proyecto' estudio.idProyecto_id %}">Detalle del proyecto</option>
    <option value="{% url 'mactor:consultar_estudio' estudio.id %}">Detalle del estudio</option>
    {% if usuario != 'EXPERTO' %}
        <option value="{% url 'mactor:actores' estudio.id %}">Actores</option>
        <option value="{% url 'mactor:fichas' estudio.id %}">Fichas de estrategias</option>
        <option value="{% url 'mactor:objetivos' estudio.id %}">Objetivos</option>
    {% endif %}
    <option value="{% url 'mactor:influenciasMID' estudio.id %}">Relaciones MID</option>
    <option value="{% url 'mactor:relacionesMAO' estudio.id %}">Relaciones MAO</option>
    {% if usuario != 'EXPERTO' %}
        <option value="{% url 'mactor:editar_informe' informe.id %}">Informe final</option>
    {% endif %}
    <option value="{% url 'mactor:exportar_excel' estudio.id %}">Descargar datos</option>
</select>