apps/mactor/urls.py
from django.conf.urls import url
from django.contrib.auth.decorators import login_required
from .views import CrearEstudio, ConsultarEstudio, EditarEstudio, EliminarEstudio, \
    ListaActores, CrearActor, EditarActor, EliminarActor, consultar_actor, importar_actores_fichas, \
    ListaFichas, CrearFicha, EditarFicha, EliminarFicha, ConsultarFicha, \
    ListaObjetivos, CrearObjetivo, EditarObjetivo, EliminarObjetivo, consultar_objetivo, importar_objetivos, \
    ListaInfluenciasMID, CrearInfluenciaMID, EditarInfluenciaMID, ConsultarInfluenciaMID, \
    generar_matriz_mid, generar_matriz_midi, generar_matriz_maxima, generar_matriz_ri, \
    generar_matriz_balance, generar_indicador_estabilidad,\
    ListaRelacionesMAO, CrearRelacionMAO, EditarRelacionMAO, \
    ConsultarRelacionMAO, generar_matriz_mao, generar_matrices_caa_daa, generar_lista_descendiente,\
    consultar_actores_faltantes, \
    EditarInformeFinal, exportar_estudio_xls, \
    histograma_mid, datos_histograma_mid, histograma_ri, datos_histograma_ri, \
    histograma_implicacion, histograma_movilizacion, datos_histogramas_mao,  \
    datos_histograma_caa_daa, histograma_caa_daa, \
    generar_mapa_midi, datos_mapa_midi, generar_mapa_caa_daa, datos_mapa_caa_daa, \
    generar_grafo_caa, datos_grafo_caa, generar_grafo_daa, datos_grafo_daa, \
    activar_consenso_mid, activar_consenso_mao, activar_consenso_caa_daa

urlpatterns = [

    # Urls modelo Estudio_mactor

    url(r'^agregar_estudio/(?P<pk>\d+)/$', login_required(CrearEstudio.as_view()), name='nuevo_estudio'),
    url(r'^consultar_estudio/(?P<pk>\d+)/$', login_required(ConsultarEstudio.as_view()), name='consultar_estudio'),
    url(r'^editar_estudio/(?P<pk>\d+)/$', login_required(EditarEstudio.as_view()), name='editar_estudio'),
    url(r'^eliminar_estudio/(?P<pk>\d+)/$', login_required(EliminarEstudio.as_view()), name='eliminar_estudio'),

    # Urls modelo Actor
    url(r'^actores/(\d+)/$', login_required(ListaActores.as_view()), name='actores'),
    url(r'^nuevo_actor/(\d+)/$', login_required(CrearActor.as_view()), name='nuevo_actor'),
    url(r'^editar_actor/(?P<pk>\d+)/$', login_required(EditarActor.as_view()), name='editar_actor'),
    url(r'^eliminar_actor/(?P<pk>\d+)/$', login_required(EliminarActor.as_view()), name='eliminar_actor'),
    url(r'consultar_actor', login_required(consultar_actor)),
    url(r'importar_actores_fichas', login_required(importar_actores_fichas)),

    # Urls modelo Ficha
    url(r'^fichas/(\d+)/$', login_required(ListaFichas.as_view()), name='fichas'),
    url(r'^nueva_ficha/(\d+)/$', login_required(CrearFicha.as_view()), name='nueva_ficha'),
    url(r'^editar_ficha/(?P<pk>\d+)/$', login_required(EditarFicha.as_view()), name='editar_ficha'),
    url(r'^consultar_ficha/(?P<pk>\d+)/$', login_required(ConsultarFicha.as_view()), name='consultar_ficha'),
    url(r'^eliminar_ficha/(?P<pk>\d+)/$', login_required(EliminarFicha.as_view()), name='eliminar_ficha'),

    # Urls modelo Objetivo
    url(r'^objetivos/(\d+)/$', login_required(ListaObjetivos.as_view()), name='objetivos'),
    url(r'^nuevo_objetivo/(\d+)/$', login_required(CrearObjetivo.as_view()), name='nuevo_objetivo'),
    url(r'^editar_objetivo/(?P<pk>\d+)/$', login_required(EditarObjetivo.as_view()), name='editar_objetivo'),
    url(r'^eliminar_objetivo/(?P<pk>\d+)/$', login_required(EliminarObjetivo.as_view()), name='eliminar_objetivo'),
    url(r'consultar_objetivo', login_required(consultar_objetivo)),
    url(r'importar_objetivos', login_required(importar_objetivos)),

    # Urls modelo RelacionMID
    url(r'^influenciasMID/(\d+)/$', login_required(ListaInfluenciasMID.as_view()), name='influenciasMID'),
    url(r'^nueva_influencia/(?P<actorY>\d+)/(?P<actorX>\d+)/$', login_required(CrearInfluenciaMID.as_view()),
        name='nueva_mid_matriz'),
    url(r'^consultar_mid/(?P<pk>\d+)/(?P<tipoAcceso>\w+)/$', login_required(ConsultarInfluenciaMID.as_view()),
        name='consultar_mid'),
    url(r'^editar_mid/(?P<pk>\d+)/(?P<tipoAcceso>\w+)/$', login_required(EditarInfluenciaMID.as_view()),
        name='editar_mid'),
    url(r'^matriz_mid/(?P<idEstudio>\d+)/$', login_required(generar_matriz_mid), name='matriz_mid'),
    url(r'^matriz_midi/(?P<idEstudio>\d+)/$', login_required(generar_matriz_midi), name='matriz_midi'),
    url(r'^matriz_maxima/(?P<idEstudio>\d+)/$', login_required(generar_matriz_maxima), name='matriz_maxima'),
    url(r'^matriz_ri/(?P<idEstudio>\d+)/$', login_required(generar_matriz_ri), name='matriz_ri'),
    url(r'^matriz_balance/(?P<idEstudio>\d+)/$', login_required(generar_matriz_balance), name='matriz_balance'),
    url(r'^estabilidad/(?P<idEstudio>\d+)/$', login_required(generar_indicador_estabilidad), name='estabilidad'),

    # Urls modelo RelacionMAO
    url(r'^relacionesMAO/(\d+)/$', login_required(ListaRelacionesMAO.as_view()), name='relacionesMAO'),
    url(r'^nueva_MAO/(?P<actor>\d+)/(?P<objetivo>\d+)/$', login_required(CrearRelacionMAO.as_view()),
        name='nueva_MAO'),
    url(r'^consultar_mao/(?P<pk>\d+)/(?P<tipoAcceso>\w+)/$', login_required(ConsultarRelacionMAO.as_view()),
        name='consultar_mao'),
    url(r'^editar_mao/(?P<pk>\d+)/(?P<tipoAcceso>\w+)/$', login_required(EditarRelacionMAO.as_view()),
        name='editar_mao'),
    url(r'^matriz_mao/(?P<idEstudio>\d+)/(?P<numero_matriz>\d)/', login_required(generar_matriz_mao),
        name='matriz_mao'),
    url(r'^matriz_caa_daa/(?P<idEstudio>\d+)/(?P<numero_matriz>\d)/$', login_required(generar_matrices_caa_daa),
        name='caa_daa'),
    url(r'^lista_descendientes/(?P<idEstudio>\d+)/(?P<numero_matriz>\d)/$', login_required(generar_lista_descendiente),
        name='descendientes'),

    # Urls modelo informe final
    url(r'^editar_informe/(?P<pk>\d+)/$', login_required(EditarInformeFinal.as_view()), name='editar_informe'),

    # Urls consultas ajax
    url(r'ficha-ajax/$', login_required(consultar_actores_faltantes)), # obtiene lista actores X registrados en la ficha

    # Urls consensos
    url(r'^consenso_mid/(?P<idEstudio>\d+)/(?P<matriz>\d)', login_required(activar_consenso_mid), name='consenso_mid'),
    url(r'^consenso_mao/(?P<idEstudio>\d+)/(?P<matriz>\d)/(?P<tipo>\d)', login_required(activar_consenso_mao),
        name='consenso_mao'),
    url(r'^consenso_caa_daa/(?P<idEstudio>\d+)/(?P<matriz>\d)/(?P<tipo>\d)', login_required(activar_consenso_caa_daa),
        name='consenso_caa_daa'),

    # Urls histogramas mid
    url(r'^histograma_mid/(?P<idEstudio>\d+)/$', login_required(histograma_mid), name='histograma_mid'),
    url(r'datos_histograma_mid', login_required(datos_histograma_mid)),
    url(r'^histograma_ri/(?P<idEstudio>\d+)/$', login_required(histograma_ri), name='histograma_ri'),
    url(r'datos_histograma_ri', login_required(datos_histograma_ri)),

    # Urls histogramas mao
    url(r'^histograma_implicacion/(?P<idEstudio>\d+)/(?P<numero_matriz>\d)/$', login_required(histograma_implicacion),
        name='implicacion'),
    url(r'^histograma_movilizacion/(?P<idEstudio>\d+)/(?P<numero_matriz>\d)/$', login_required(histograma_movilizacion),
        name='movilizacion'),
    url(r'datos_histograma', login_required(datos_histogramas_mao)),

    # Urls mapa actores
    url(r'^mapa_actores/(?P<idEstudio>\d+)/$', login_required(generar_mapa_midi), name='mapa_actores'),
    url(r'datos_plano_midi', login_required(datos_mapa_midi)),

    # Urls graficos caa y daa
    url(r'^mapa_caa_daa/(?P<idEstudio>\d+)/(?P<numero_matriz>\d)/$', login_required(generar_mapa_caa_daa),
        name='mapa_caa_daa'),
    url(r'datos_mapa_caa_daa', login_required(datos_mapa_caa_daa)),
    url(r'^histograma_caa_daa/(?P<idEstudio>\d+)/(?P<numero_matriz>\d)/$', login_required(histograma_caa_daa),
        name='hist_caa_daa'),
    url(r'datos_caa_daa', login_required(datos_histograma_caa_daa)),
    url(r'^grafo_caa/(?P<idEstudio>\d+)/(?P<numero_matriz>\d)$', login_required(generar_grafo_caa), name='grafo_caa'),
    url(r'datos_grafo_caa', login_required(datos_grafo_caa)),
    url(r'^grafo_daa/(?P<idEstudio>\d+)/(?P<numero_matriz>\d)$', login_required(generar_grafo_daa), name='grafo_daa'),
    url(r'datos_grafo_daa', login_required(datos_grafo_daa)),

    # Urls exportar a excel
    url(r'exportar_estudios/xls/(?P<idEstudio>\d+)/$', login_required(exportar_estudio_xls), name='exportar_excel'),

]

softprosp/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from apps.usuario.views import UserRegistrationView

urlpatterns = [
  url(r'^admin/', admin.site.urls),
  # sobreescritura del formulario de registro de registration-redux
  url(r'^accounts/register/$', UserRegistrationView.as_view(),
      name='registration_register'),
  url(r'^proyecto/', include('apps.proyecto.urls', namespace="proyecto")),
  url(r'^usuario/', include('apps.usuario.urls', namespace="usuario")),
  url(r'^abaco/', include('apps.abaco.urls', namespace="abaco")),
  url(r'^delphi/', include('apps.delphi.urls', namespace="delphi")),
  url(r'^entrevista/', include('apps.entrevista.urls', namespace="entrevista")),
  url(r'^brainstorming/',
      include('apps.brainstorming.urls', namespace="brainstorming")),
  url(r'^mactor/', include('apps.mactor.urls', namespace="mactor")),
  url(r'^multipol/', include('apps.multipolv1.urls', namespace='multipol')),
  url(r'^extrapolacion', include('apps.extrapolacion_tendencias.urls',
                                 namespace='extrapolacion')),
  # urls vista control de usuarios paquete Registration redux
  url(r'^accounts/', include('registration.backends.default.urls')),
]

apps/mactor/models.py
from django.db import models
from ..proyecto.models import Proyecto, Tecnica
from django.contrib.auth.models import User
from django.utils.timezone import now
from django.core.urlresolvers import reverse

"""MODELO ESTUDIO MACTOR--------------------------------------------------------------------------------------------"""


class EstudioMactor(models.Model):

    tipoTecnica = models.ForeignKey(Tecnica, null=True) # el tipo se agrega mandando e objeto por contexto
    titulo = models.CharField(max_length=200)
    descripcion = models.TextField()
    idAdministrador = models.ForeignKey(User, verbose_name='administrador', related_name='mactor_administrador')
    idCoordinador = models.ForeignKey(User, verbose_name='coordinador', related_name='mactor_coordinador')
    idExpertos = models.ManyToManyField(User, verbose_name='Expertos', related_name='mactor_expertos_set')
    fecha_inicio = models.DateField(default=now)
    fecha_final = models.DateField(default=now)
    dias_finalizacion_informe = models.PositiveIntegerField(default=5)
    estado = models.BooleanField(default=True)
    idProyecto = models.ForeignKey(Proyecto, null=True, on_delete=models.CASCADE)

# Definicion de nombre singular y plural del modelo
    class Meta:
        verbose_name = 'Estudio Mactor'
        verbose_name_plural = 'Estudios Mactor'
        unique_together = [('titulo', 'tipoTecnica', 'idProyecto')]

    def get_absolute_url(self):
        return reverse('proyecto:ver_estudios_proyecto', args={self.idProyecto.id})

# Campo a mostrar del modelo Estudio_Mactor (tabla en admin y listas desplegables)
    def __str__(self):
        return u'{0}'.format(self.titulo)


"""MODELO ACTOR-----------------------------------------------------------------------------------------------------"""


class Actor(models.Model):

    nombreLargo = models.CharField(max_length=100)
    nombreCorto = models.CharField(max_length=5)
    descripcion = models.TextField(max_length=200, null=True, blank=True)
    idEstudio = models.ForeignKey(EstudioMactor, default=0, on_delete=models.CASCADE)

    class Meta:
        verbose_name = 'Actor'
        verbose_name_plural = 'Actores'
        unique_together = [('nombreLargo', 'nombreCorto', 'idEstudio'),
                           ('nombreLargo', 'idEstudio'),
                           ('nombreCorto', 'idEstudio')]

    def get_absolute_url(self):
        return reverse('mactor:actores', args={self.idEstudio.id})

    def __str__(self):
        return u'{0} - {1}'.format(self.nombreCorto, self.nombreLargo)


"""MODELO FICHA DE ESTRATEGIAS--------------------------------------------------------------------------------------"""


class Ficha(models.Model):

    idActorY = models.ForeignKey(Actor, default=0, related_name='mactor_actorY_ficha', on_delete=models.CASCADE)
    idActorX = models.ForeignKey(Actor, default=0, related_name='mactor_actorX_ficha', on_delete=models.CASCADE)
    estrategia = models.TextField(default="", blank=False)

    class Meta:
        verbose_name = 'Ficha de estrategias'
        verbose_name_plural = 'Fichas de estrategia'
        unique_together = ('idActorY', 'idActorX')

    def __str__(self):
        return u'{0} - {1} - {2}'.format(self.idActorX, self.idActorY, self.estrategia)


"""MODELO OBJETIVO--------------------------------------------------------------------------------------------------"""


class Objetivo(models.Model):

    nombreLargo = models.CharField(max_length=100)
    nombreCorto = models.CharField(max_length=5)
    descripcion = models.TextField(max_length=500, null=True, blank=True)
    idEstudio = models.ForeignKey(EstudioMactor, default=0, on_delete=models.CASCADE)

    class Meta:
        verbose_name = 'Objetivo'
        verbose_name_plural = 'Objetivos'
        unique_together = [('nombreLargo', 'nombreCorto', 'idEstudio'),
                           ('nombreLargo', 'idEstudio'),
                           ('nombreCorto', 'idEstudio')]

    def get_absolute_url(self):
        return reverse('mactor:objetivos', args={self.idEstudio.id})

    def __str__(self):
        return u'{0} - {1}'.format(self.nombreCorto, self.nombreLargo)


"""MODELO RELACIONES DE INFLUENCIA DIRECTA---------------------------------------------------------------------------"""


class RelacionMID(models.Model):

    idActorX = models.ForeignKey(Actor, default=0, related_name='mactor_actorX_set', on_delete=models.CASCADE)
    idActorY = models.ForeignKey(Actor, default=0, blank=False, related_name='mactor_actorY_set', on_delete=models.CASCADE)
    valor = models.IntegerField()
    justificacion = models.TextField(default="Justificación de la relación entre los actores")
    idExperto = models.ForeignKey(User, null=True)

    class Meta:
        verbose_name = 'Relacion de Influencia'
        verbose_name_plural = 'Relaciones de influencia'
        unique_together = ('idActorX', 'idActorY', 'idExperto')

    def __str__(self):
        return u'{0} - {1} - {2}'.format(self.idActorY, self.idActorX, self.valor)


"""MODELO RELACIONES DE ACTOR x OBJETIVO---------------------------------------------------------------------------"""


class RelacionMAO(models.Model):

    tipo = models.IntegerField(null=True, blank=True)
    idActorY = models.ForeignKey(Actor, default=0, on_delete=models.CASCADE)
    idObjetivoX = models.ForeignKey(Objetivo, default=0, on_delete=models.CASCADE)
    valor = models.IntegerField()
    justificacion = models.TextField(default="Justificación de la relación entre el actor y el objetivo")
    idExperto = models.ForeignKey(User, null=True)

    class Meta:
        verbose_name = 'Relacion MAO'
        verbose_name_plural = 'Relaciones MAO'
        unique_together = ('tipo', 'idActorY', 'idObjetivoX', 'idExperto')

    def __str__(self):
        return u'{0} - {1} - {2} - {3} - {4}'.format(self.tipo, self.idActorY, self.idObjetivoX, self.valor, self.idExperto)


"""MODELO INFORME FINAL---------------------------------------------------------------------------------------------"""


class InformeFinal(models.Model):

    fecha = models.DateTimeField(auto_now=True)
    informe = models.TextField()
    estado = models.BooleanField(default=False)
    idEstudio = models.ForeignKey(EstudioMactor, default=0, on_delete=models.CASCADE)

    class Meta:
        verbose_name = 'Informe final'
        verbose_name_plural = 'Informes finales'

    def __str__(self):
        return u'{0} - {1} - {2}'.format(self.idEstudio, self.fecha, self.informe, self.estado)


# Sobreescritura del modelo usuario


def get_name(self):
    if self.first_name != '':
        return '{} {}'.format(self.first_name, self.last_name)
    else:
        return '{}'.format(self.username)

User.add_to_class("__str__", get_name)

templates/mactor/ficha/consultar_ficha.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block content %}
    {% if usuario != '' %}
            <div class="matter">
            <div class="container">
                <div class="row">
                    <div class="col-md-12">
                            <div class="widget-head">
                                <div class="box-header with-border">
                                  <h3 class="box-title">Detalle ficha de estrategias </h3>
                                </div>
                            </div>
                            <div class="widget-content">
                                <div class="padd">
										<hr/>
										<!-- Form starts.  -->
                                    <form class="form-horizontal" role="form" method="post">
                                        {% csrf_token %}

                                        <div class="row">
                                            <div class="col-md-8 col-md-offset-1">
                                                <div class="form-group">
                                                    <label class="control-label" style="text-align: left">Estrategias del actor</label>
                                                    <input class="form-control" readonly value="{{ ficha.idActorY }}">
                                                </div>
                                            </div>
                                        </div>

                                        <div class="row">
                                            <div class="col-md-8 col-md-offset-1">
                                                <div class="form-group">
                                                    <label class="control-label" style="text-align: left">Sobre el actor</label>
                                                    <input class="form-control" readonly value="{{ ficha.idActorX }}">
                                                </div>
                                            </div>
                                        </div>

                                        <div class="row">
                                            <div class="col-md-8 col-md-offset-1">
                                                <div class="form-group">
                                                    <label class="control-label" style="text-align: left">Estrategias</label>
                                                    <textarea class="form-control" rows="10" readonly>{{ ficha.estrategia }}</textarea>
                                                </div>
                                            </div>
                                        </div>

                                         <div class="form-group">
                                            <div class="col-md-8 col-md-offset-3">
                                                <a class="btn btn-success" href="{% url 'mactor:fichas' ficha.idActorX.idEstudio.id %}" title="Fichas de estrategias"><i class="fa fa-arrow-left"></i> Atrás</a>
                                            </div>
                                        </div>

                                    </form>

                                </div>
                            </div>
                    </div>
                </div>

            </div>
</div>

    {% else %}
        <h2>No cuenta con permisos para acceder a esta página.</h2>
    {% endif %}
{% endblock %}

templates/mactor/ficha/eliminar_ficha.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block content %}
    {% if ficha.idActorX.idEstudio.estado and usuario != 'EXPERTO' and usuario != '' %}
        <div class="matter">
            <div class="container">
                <div class="row">
                    <div class="col-md-12">
                            <div class="widget-head">
                                <div class="box-header with-border">
                                  <h3 class="box-title">Eliminar Ficha de estrategias</h3>
                                </div>
                            </div>
                            <div class="widget-content">
                                <div class="padd">
										<hr/>
										<!-- Form starts.  -->
                                    <form class="form-horizontal" role="form" method="post">
                                        {% csrf_token %}
                                        <h3>¿Desea eliminar esta ficha de estrategias?</h3>

                                        <div class="row">
                                            <div class="col-md-8 col-md-offset-1">
                                                <div class="form-group">
                                                    <label class="control-label" style="text-align: left">Estrategias del actor</label>
                                                    <input class="form-control" readonly value="{{ ficha.idActorY }}">
                                                </div>
                                            </div>
                                        </div>

                                        <div class="row">
                                            <div class="col-md-8 col-md-offset-1">
                                                <div class="form-group">
                                                    <label class="control-label" style="text-align: left">Sobre el actor</label>
                                                    <input class="form-control" readonly value="{{ ficha.idActorX }}">
                                                </div>
                                            </div>
                                        </div>

                                        <div class="row">
                                            <div class="col-md-8 col-md-offset-1">
                                                <div class="form-group">
                                                    <label class="control-label" style="text-align: left">Estrategias</label>
                                                    <textarea class="form-control" rows="5" readonly>{{ ficha.estrategia }}</textarea>
                                                </div>
                                            </div>
                                        </div>

                                        <div class="form-group">
                                            <div class="col-md-8 col-md-offset-3" style="align-content: center">
                                                <a class="btn btn-success" href="{% url 'mactor:fichas' ficha.idActorX.idEstudio.id %}"><i class="fa fa-arrow-left"></i> Cancelar</a>
                                                <button type="submit" class="btn btn-danger" title="Eliminar"><i class="fa fa-trash"></i> Si, eliminar</button>
                                            </div>
                                        </div>
                                    </form>

                                </div>
                            </div>
                    </div>
                </div>
            </div>
</div>
    {% else %}
        <h2>No cuenta con permisos para acceder a esta página.</h2>
    {% endif %}

{% endblock %}

templates/mactor/ficha/lista_fichas.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block extra_css %}
     <!-- DataTables -->
    <link rel="stylesheet" href="{% static 'css/dataTables.bootstrap.min.css' %}">

    <style>
        #tabla_fichas th, td {text-align: center}
    </style>
{% endblock%}

{% block content %}
    {% if usuario != '' and usuario != 'EXPERTO' %}

        {% include 'messages.html' %}

        <div class="box">
            <div class="box-header">
              <h3 class="box-title">Estrategias de los actores</h3>

                {% include 'mactor/estudio/select_datos_estudio.html' %}
            </div>
            <!-- /.box-header -->
            <div class="box-body">
               {% if fichas %}

              <table id="tabla_fichas" class="table table-bordered table-striped">
                <thead>
                <tr>
                  <th>#</th>
                  <th>Estrategias del actor</th>
                  <th>Sobre el actor</th>
                  <th>Estrategias</th>
                  <th id="acciones" style="text-align: center">Acciones</th>
                </tr>
                </thead>
                <tbody>
                    {% for ficha in fichas %}
                        <tr>
                            <td>{{forloop.counter}}</td>
                            <td>{{ficha.idActorY.nombreLargo}}</td>
                            <td>{{ficha.idActorX.nombreLargo}}</td>
                            <td style="text-align: justify">{{ficha.estrategia|truncatechars:100}}</td>
                            <td style="width: 15%">
                                <a  id="{{ actor.id }}" class="btn btn-primary" href="{% url 'mactor:consultar_ficha' ficha.id %}" title="Ver" data-toggle="modal"><i class="fa fa-eye"></i></a>
                                {% if estudio.estado %}
                                    <a class="btn btn-warning .edit" href="{% url 'mactor:editar_ficha' ficha.id %}" title="Editar"><i class="fa fa-pencil"></i></a>
                                    <a class="btn btn-danger delete" href="{% url 'mactor:eliminar_ficha' ficha.id %}" title="Eliminar"><i class="fa fa-trash"></i></a>
                                {% else %}
                                    <a class="btn btn-warning .edit" disabled="True" title="El estudio se encuentra cerrado."><i class="fa fa-pencil"></i></a>
                                    <a class="btn btn-danger delete" disabled="True" title="El estudio se encuentra cerrado."><i class="fa fa-trash"></i></a>
                                {% endif %}
                            </td>
                        </tr>
                    {% endfor %}
                {% else %}
                    <h3>No existen fichas de estrategias registradas.</h3>
                {% endif %}
                </tfoot>
              </table>

            <!--BOTONES --------------------------------- -->

                <div class="form-group">
                    <div class="col-md-offset-2 col-md-8">
                            {% if estudio.estado and incompletos > 0 %}
                                <a class="btn btn-primary" href="{% url 'mactor:nueva_ficha' estudio.id %}" title="Agregar actor"><i class="fa fa-plus"></i> Agregar</a>
                            {% else %}
                                <a class="btn btn-primary" disabled="True"
                                   {% if estudio.estado is False %}
                                        title="El estudio se encuentra cerrado."
                                   {% else %}
                                        title="Ha registrado todas las fichas de estrategias."
                                   {% endif %}
                                ><i class="fa fa-plus"></i> Agregar</a>

                        {% endif %}
                        <a class="btn btn-primary" data-toggle="modal" href="#modalAyuda" title="Ayuda"><i class="fa fa-book"></i> Ayuda</a>
                    </div>
                </div>

             <!--MODAL AYUDA------------------------- -->

		    <div id="modalAyuda" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
				  <div class="modal-dialog">
					  <div class="modal-content">
						  <div class="modal-header">
							  <button type="button" class="close" data-dismiss="modal" aria-hidden="true">X</button>
							  <h4 class="modal-title">Ayuda - Estrategias de los actores</h4>
						  </div>
						  <div class="modal-body" style="text-align: justify">
							  <p>La tabla de estrategias de los actores describe los planes, motivaciones, limitaciones y
								  medios de acción de cada actor. La información de la influencia de un actor sobre si
								  mismo corresponde a una "tarjeta de identidad" que puede incluir información asociada
								  a las metas, fortalezas, debilidades del actor, siendo estos registros generalmente los
								  mas completos. Por el contrario, muchas de las acciones de un actor hacia otro se
								  encuentran casi o totalmente vacías, estas describen los medios de acción que cada actor
								  puede utilizar contra los otros a fin de alcanzar sus metas.
								  <br>
								  La información proporcionada por técnicas preliminares como MICMAC se utiliza para
								  completar la mayor parte de la tabla, el resto contendría el resultado de entrevistas
								  más exhaustivas, recordandose que la calidad de los resultados a alcanzar dependerá
								  de la información recolectada(LIPSOR-EPITA, s.f).
							  </p>
						  </div>
						  <div class="modal-footer">
							  <button type="button" class="btn btn-default" data-dismiss="modal" aria-hidden="true">Cerrar</button>
						  </div>
					  </div>
				  </div>
			  </div>

            </div>
            <!-- /.box-body -->
          </div>

    {% else %}
        <h2>No cuenta con permisos para acceder a esta página.</h2>
    {% endif %}

{% endblock %}

{% block extra_js %}
     <!-- DataTables -->
    <script src="{% static 'js/jquery.dataTables.min.js' %}"></script>
    <script src="{% static 'js/dataTables.bootstrap.min.js' %}"></script>
    <script>
      $(function () {
        $('#tabla_fichas').DataTable({
          'paging'      : true,
          'lengthChange': true,
          'searching'   : true,
          'ordering'    : false,
          'info'        : true,
          'autoWidth'   : true,
          'aLengthMenu' : [[5, 10, 50, -1], [5, 10, 50, "All"]]
        })
      })
    </script>
{% endblock %}