apps/mactor/urls.py
from django.conf.urls import url
from django.contrib.auth.decorators import login_required
from .views import CrearEstudio, ConsultarEstudio, EditarEstudio, EliminarEstudio, \
    ListaActores, CrearActor, EditarActor, EliminarActor, consultar_actor, importar_actores_fichas, \
    ListaFichas, CrearFicha, EditarFicha, EliminarFicha, ConsultarFicha, \
    ListaObjetivos, CrearObjetivo, EditarObjetivo, EliminarObjetivo, consultar_objetivo, importar_objetivos, \
    ListaInfluenciasMID, CrearInfluenciaMID, EditarInfluenciaMID, ConsultarInfluenciaMID, \
    generar_matriz_mid, generar_matriz_midi, generar_matriz_maxima, generar_matriz_ri, \
    generar_matriz_balance, generar_indicador_estabilidad,\
    ListaRelacionesMAO, CrearRelacionMAO, EditarRelacionMAO, \
    ConsultarRelacionMAO, generar_matriz_mao, generar_matrices_caa_daa, generar_lista_descendiente,\
    consultar_actores_faltantes, \
    EditarInformeFinal, exportar_estudio_xls, \
    histograma_mid, datos_histograma_mid, histograma_ri, datos_histograma_ri, \
    histograma_implicacion, histograma_movilizacion, datos_histogramas_mao,  \
    datos_histograma_caa_daa, histograma_caa_daa, \
    generar_mapa_midi, datos_mapa_midi, generar_mapa_caa_daa, datos_mapa_caa_daa, \
    generar_grafo_caa, datos_grafo_caa, generar_grafo_daa, datos_grafo_daa, \
    activar_consenso_mid, activar_consenso_mao, activar_consenso_caa_daa

urlpatterns = [

    # Urls modelo Estudio_mactor

    url(r'^agregar_estudio/(?P<pk>\d+)/$', login_required(CrearEstudio.as_view()), name='nuevo_estudio'),
    url(r'^consultar_estudio/(?P<pk>\d+)/$', login_required(ConsultarEstudio.as_view()), name='consultar_estudio'),
    url(r'^editar_estudio/(?P<pk>\d+)/$', login_required(EditarEstudio.as_view()), name='editar_estudio'),
    url(r'^eliminar_estudio/(?P<pk>\d+)/$', login_required(EliminarEstudio.as_view()), name='eliminar_estudio'),

    # Urls modelo Actor
    url(r'^actores/(\d+)/$', login_required(ListaActores.as_view()), name='actores'),
    url(r'^nuevo_actor/(\d+)/$', login_required(CrearActor.as_view()), name='nuevo_actor'),
    url(r'^editar_actor/(?P<pk>\d+)/$', login_required(EditarActor.as_view()), name='editar_actor'),
    url(r'^eliminar_actor/(?P<pk>\d+)/$', login_required(EliminarActor.as_view()), name='eliminar_actor'),
    url(r'consultar_actor', login_required(consultar_actor)),
    url(r'importar_actores_fichas', login_required(importar_actores_fichas)),

    # Urls modelo Ficha
    url(r'^fichas/(\d+)/$', login_required(ListaFichas.as_view()), name='fichas'),
    url(r'^nueva_ficha/(\d+)/$', login_required(CrearFicha.as_view()), name='nueva_ficha'),
    url(r'^editar_ficha/(?P<pk>\d+)/$', login_required(EditarFicha.as_view()), name='editar_ficha'),
    url(r'^consultar_ficha/(?P<pk>\d+)/$', login_required(ConsultarFicha.as_view()), name='consultar_ficha'),
    url(r'^eliminar_ficha/(?P<pk>\d+)/$', login_required(EliminarFicha.as_view()), name='eliminar_ficha'),

    # Urls modelo Objetivo
    url(r'^objetivos/(\d+)/$', login_required(ListaObjetivos.as_view()), name='objetivos'),
    url(r'^nuevo_objetivo/(\d+)/$', login_required(CrearObjetivo.as_view()), name='nuevo_objetivo'),
    url(r'^editar_objetivo/(?P<pk>\d+)/$', login_required(EditarObjetivo.as_view()), name='editar_objetivo'),
    url(r'^eliminar_objetivo/(?P<pk>\d+)/$', login_required(EliminarObjetivo.as_view()), name='eliminar_objetivo'),
    url(r'consultar_objetivo', login_required(consultar_objetivo)),
    url(r'importar_objetivos', login_required(importar_objetivos)),

    # Urls modelo RelacionMID
    url(r'^influenciasMID/(\d+)/$', login_required(ListaInfluenciasMID.as_view()), name='influenciasMID'),
    url(r'^nueva_influencia/(?P<actorY>\d+)/(?P<actorX>\d+)/$', login_required(CrearInfluenciaMID.as_view()),
        name='nueva_mid_matriz'),
    url(r'^consultar_mid/(?P<pk>\d+)/(?P<tipoAcceso>\w+)/$', login_required(ConsultarInfluenciaMID.as_view()),
        name='consultar_mid'),
    url(r'^editar_mid/(?P<pk>\d+)/(?P<tipoAcceso>\w+)/$', login_required(EditarInfluenciaMID.as_view()),
        name='editar_mid'),
    url(r'^matriz_mid/(?P<idEstudio>\d+)/$', login_required(generar_matriz_mid), name='matriz_mid'),
    url(r'^matriz_midi/(?P<idEstudio>\d+)/$', login_required(generar_matriz_midi), name='matriz_midi'),
    url(r'^matriz_maxima/(?P<idEstudio>\d+)/$', login_required(generar_matriz_maxima), name='matriz_maxima'),
    url(r'^matriz_ri/(?P<idEstudio>\d+)/$', login_required(generar_matriz_ri), name='matriz_ri'),
    url(r'^matriz_balance/(?P<idEstudio>\d+)/$', login_required(generar_matriz_balance), name='matriz_balance'),
    url(r'^estabilidad/(?P<idEstudio>\d+)/$', login_required(generar_indicador_estabilidad), name='estabilidad'),

    # Urls modelo RelacionMAO
    url(r'^relacionesMAO/(\d+)/$', login_required(ListaRelacionesMAO.as_view()), name='relacionesMAO'),
    url(r'^nueva_MAO/(?P<actor>\d+)/(?P<objetivo>\d+)/$', login_required(CrearRelacionMAO.as_view()),
        name='nueva_MAO'),
    url(r'^consultar_mao/(?P<pk>\d+)/(?P<tipoAcceso>\w+)/$', login_required(ConsultarRelacionMAO.as_view()),
        name='consultar_mao'),
    url(r'^editar_mao/(?P<pk>\d+)/(?P<tipoAcceso>\w+)/$', login_required(EditarRelacionMAO.as_view()),
        name='editar_mao'),
    url(r'^matriz_mao/(?P<idEstudio>\d+)/(?P<numero_matriz>\d)/', login_required(generar_matriz_mao),
        name='matriz_mao'),
    url(r'^matriz_caa_daa/(?P<idEstudio>\d+)/(?P<numero_matriz>\d)/$', login_required(generar_matrices_caa_daa),
        name='caa_daa'),
    url(r'^lista_descendientes/(?P<idEstudio>\d+)/(?P<numero_matriz>\d)/$', login_required(generar_lista_descendiente),
        name='descendientes'),

    # Urls modelo informe final
    url(r'^editar_informe/(?P<pk>\d+)/$', login_required(EditarInformeFinal.as_view()), name='editar_informe'),

    # Urls consultas ajax
    url(r'ficha-ajax/$', login_required(consultar_actores_faltantes)), # obtiene lista actores X registrados en la ficha

    # Urls consensos
    url(r'^consenso_mid/(?P<idEstudio>\d+)/(?P<matriz>\d)', login_required(activar_consenso_mid), name='consenso_mid'),
    url(r'^consenso_mao/(?P<idEstudio>\d+)/(?P<matriz>\d)/(?P<tipo>\d)', login_required(activar_consenso_mao),
        name='consenso_mao'),
    url(r'^consenso_caa_daa/(?P<idEstudio>\d+)/(?P<matriz>\d)/(?P<tipo>\d)', login_required(activar_consenso_caa_daa),
        name='consenso_caa_daa'),

    # Urls histogramas mid
    url(r'^histograma_mid/(?P<idEstudio>\d+)/$', login_required(histograma_mid), name='histograma_mid'),
    url(r'datos_histograma_mid', login_required(datos_histograma_mid)),
    url(r'^histograma_ri/(?P<idEstudio>\d+)/$', login_required(histograma_ri), name='histograma_ri'),
    url(r'datos_histograma_ri', login_required(datos_histograma_ri)),

    # Urls histogramas mao
    url(r'^histograma_implicacion/(?P<idEstudio>\d+)/(?P<numero_matriz>\d)/$', login_required(histograma_implicacion),
        name='implicacion'),
    url(r'^histograma_movilizacion/(?P<idEstudio>\d+)/(?P<numero_matriz>\d)/$', login_required(histograma_movilizacion),
        name='movilizacion'),
    url(r'datos_histograma', login_required(datos_histogramas_mao)),

    # Urls mapa actores
    url(r'^mapa_actores/(?P<idEstudio>\d+)/$', login_required(generar_mapa_midi), name='mapa_actores'),
    url(r'datos_plano_midi', login_required(datos_mapa_midi)),

    # Urls graficos caa y daa
    url(r'^mapa_caa_daa/(?P<idEstudio>\d+)/(?P<numero_matriz>\d)/$', login_required(generar_mapa_caa_daa),
        name='mapa_caa_daa'),
    url(r'datos_mapa_caa_daa', login_required(datos_mapa_caa_daa)),
    url(r'^histograma_caa_daa/(?P<idEstudio>\d+)/(?P<numero_matriz>\d)/$', login_required(histograma_caa_daa),
        name='hist_caa_daa'),
    url(r'datos_caa_daa', login_required(datos_histograma_caa_daa)),
    url(r'^grafo_caa/(?P<idEstudio>\d+)/(?P<numero_matriz>\d)$', login_required(generar_grafo_caa), name='grafo_caa'),
    url(r'datos_grafo_caa', login_required(datos_grafo_caa)),
    url(r'^grafo_daa/(?P<idEstudio>\d+)/(?P<numero_matriz>\d)$', login_required(generar_grafo_daa), name='grafo_daa'),
    url(r'datos_grafo_daa', login_required(datos_grafo_daa)),

    # Urls exportar a excel
    url(r'exportar_estudios/xls/(?P<idEstudio>\d+)/$', login_required(exportar_estudio_xls), name='exportar_excel'),

]

softprosp/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from apps.usuario.views import UserRegistrationView

urlpatterns = [
  url(r'^admin/', admin.site.urls),
  # sobreescritura del formulario de registro de registration-redux
  url(r'^accounts/register/$', UserRegistrationView.as_view(),
      name='registration_register'),
  url(r'^proyecto/', include('apps.proyecto.urls', namespace="proyecto")),
  url(r'^usuario/', include('apps.usuario.urls', namespace="usuario")),
  url(r'^abaco/', include('apps.abaco.urls', namespace="abaco")),
  url(r'^delphi/', include('apps.delphi.urls', namespace="delphi")),
  url(r'^entrevista/', include('apps.entrevista.urls', namespace="entrevista")),
  url(r'^brainstorming/',
      include('apps.brainstorming.urls', namespace="brainstorming")),
  url(r'^mactor/', include('apps.mactor.urls', namespace="mactor")),
  url(r'^multipol/', include('apps.multipolv1.urls', namespace='multipol')),
  url(r'^extrapolacion', include('apps.extrapolacion_tendencias.urls',
                                 namespace='extrapolacion')),
  # urls vista control de usuarios paquete Registration redux
  url(r'^accounts/', include('registration.backends.default.urls')),
]

templates/mactor/mid/matrices/indicador_estabilidad.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block content %}
    {% if usuario != '' %}
        {% if consenso and usuario == 'EXPERTO' %}
            <h2>No cuenta con permisos para acceder a esta página.</h2>
        {% else %}
            <div class="box">
                <div class="box-header">
                    {% if consenso %}
                        <h3 class="box-title">CONSENSO - Indicador de Estabilidad de las Relaciones entre Actores</h3>
                    {% else %}
                        <h3 class="box-title">H - Indicador de Estabilidad de las Relaciones entre Actores</h3>
                    {% endif %}
                    <input hidden class="col-sm-1" type="number" name="idEstudio" value="{{estudio.id}}">
                </div>

                <!-- /.box-header -->
                <div class="box-body">

                    <div class="alert alert-info alert-dismissible">
                        <div class="row">
                            <div class="col-md-7 col-md-offset-1">
                                <div class="form-group">
                                    <h2>H = {{indicador}}%</h2>
                                </div>
                            </div>
                        </div>

                    <br>
                    {% if consenso is True %}
                        <br>
                        <h4>Expertos en consenso = {{expertos}}</h4>
                    {% endif %}
                    </div>
                    <br>


                <!--BOTONES ------------------------------ -->

                    <div class="form-group">
                        <div class="col-md-offset-2 col-md-8">
                            {% if expertos and usuario == 'COORDINADOR_EXPERTO' %}
                                <a class="btn btn-success" href="{% url 'mactor:consenso_mid' estudio.id 2 %}" title="Matriz MIDI consenso"><i class="fa fa-arrow-left"></i> Atrás</a>
                            {% else %}
                                <a class="btn btn-success" href="{% url 'mactor:matriz_midi' estudio.id %}" title="Matriz MIDI"><i class="fa fa-arrow-left"></i> Atrás</a>
                            {% endif %}
                            <a class="btn btn-primary" data-toggle="modal" href="#modalAyuda" title="Ayuda"><i class="fa fa-book"></i> Ayuda</a>
                        </div>
                    </div>


                 <!--MODAL AYUDA------------------------- -->

                <div id="modalAyuda" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
                      <div class="modal-dialog">
                          <div class="modal-content">
                              <div class="modal-header">
                                  <button type="button" class="close" data-dismiss="modal" aria-hidden="true">X</button>
                                  <h4 class="modal-title">Ayuda - Coeficiente de estabilidad H</h4>
                              </div>
                              <div class="modal-body" style="text-align: justify">
                                <p>De acuerdo a Castro y Perestrelo (2000), la estabilidad de las relaciones entre
                                    los actores se puede establecer inicialmente mediante el posicionamiento de
                                    estos en el Mapa de Influencia / Dependencia asi:<br>
                                  <i class="fa fa-check"></i> El juego de actores es estable si por un lado se tienen actores muy influyentes
                                  y poco dependientes y por otro, actores muy dependientes y poco influyentes.<br>
                                  <i class="fa fa-check"></i> El juego de actores es inestable cuando todos los actores son muy influyentes
                                  y muy dependientes, es decir ninguno tiene el poder.
                                </p>
                                  <p>
                                      El indicador de estabilidad H varía entre 0 y 100% y se calcula a partir de
                                      los valores de influencia y dependencia de MIDI entonces:<br>
                                      <i class="fa fa-check"></i> Si H ≅ 0%, es inestable, pues los actores son a la vez muy influyentes y muy dependientes.<br>
                                      <i class="fa fa-check"></i> Si H ≅ 100% es estable, ya que los actores o son muy influyentes o muy dependientes.
                                  </p>
                              </div>
                              <div class="modal-footer">
                                  <button type="button" class="btn btn-default" data-dismiss="modal" aria-hidden="true">Cerrar</button>
                              </div>
                          </div>
                      </div>
                  </div>

                </div>
                <!-- /.box-body -->
              </div>
        {% endif %}
    {% else %}
        <h2>No cuenta con permisos para acceder a esta página.</h2>
    {% endif %}

{% endblock %}

templates/mactor/mid/matrices/matriz_MID.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block extra_css %}
    <style>
        input { text-align: center; width: 60px; }
        .ejes_diagonal_gris { background-color: #5e5e5e; color: white;}
    </style>
{% endblock %}

{% block content %}
    {% if usuario != '' %}
        {% if consenso and usuario == 'EXPERTO' %}
            <h2>No cuenta con permisos para acceder a esta página.</h2>
        {% else %}
            <div class="box">
            <div class="box-header">
                {% if consenso %}
                    <h3 class="box-title"> CONSENSO - Matriz de Influencias Directas</h3>
                {% else %}
                    <h3 class="box-title">MID - Matriz de Influencias Directas ({{porcentaje}}% diligenciada)</h3>
                {% endif %}

                <div class="pull-right">
                    <select name="graficos_midi" class="form-control" onchange="location = this.value;">
                        <option value="">Análisis MID</option>
                        {% if consenso %}
                            <option value="{% url 'mactor:consenso_mid' estudio.id 7 %}">Histograma Influencia - Dependencia</option>
                        {% elif porcentaje >= 100 %}
                            <option value="{% url 'mactor:histograma_mid' estudio.id %}">Histograma Influencia - Dependencia</option>
                        {% elif consenso is False and porcentaje < 100 %}
                            <option disabled title="Finalice la Matriz de Influencias Directas para acceder">Histograma Influencia - Dependencia</option>
                        {% endif %}
                    </select>
                </div>
            </div>

            <div class="row">
                <div class="col-md-10 col-md-offset-1">
                    {% include 'messages.html' %}
                </div>
            </div>


            <!-- /.box-header -->
            <div class="box-body">

              <table class="table table-bordered table-hover" id="matriz_mid">
                  <thead>
                    <tr>
                        {%if actores and matriz %}
                            <input class="ejes_diagonal_gris" type="text" value="">
                            {% for actor in actores %}
                                <input name="actor{{actor.id}}" title="{{actor.nombreLargo|upper}}" class="ejes_diagonal_gris"
                                       value="{{actor.nombreCorto}}" data-toggle="modal" href="#modal_ConsultarActor">
                            {% endfor %}
                            <input class="ejes_diagonal_gris" type="text" title="INFLUENCIA DIRECTA" value="I.D">
                        {% endif %}
                        <br>
                    </tr>
                  </thead>
                  <tbody>
                    {% if matriz %}
                        {% for fila in matriz %}
                            {% for celda in fila %}
                                 <tr>
                                    {% if celda.posicion == 0 and celda.valor != 'D.D' %}
                                        <input name="actor{{celda.pk}}" class="ejes_diagonal_gris" title="{{celda.descripcion|upper}}"
                                                   value="{{celda.valor}}" data-toggle="modal" href="#modal_ConsultarActor">
                                    {% elif celda.valor == 'D.D' %}
                                         <input class="button_active ejes_diagonal_gris" title="{{celda.descripcion}}" value="{{celda.valor}}">
                                    {% else %}
                                        <!-- para los valores no registrados-->
                                         {% if celda.valor == 100 %}
                                             {% if celda.y != celda.x %}
                                                 <input class="button_active ejes_diagonal_gris"
                                                        {% if consenso is False and estudio.estado %}
                                                            onclick="location.href='{% url 'mactor:nueva_mid_matriz' celda.y celda.x %}'"
                                                        {% elif consenso is False and estudio.estado is False %}
                                                            data-toggle="modal" href="#modal_estado_estudio"
                                                        {% endif %}
                                                        type="text" title="Influencia sin registrar" value="X">
                                             <!-- diagonal cuando la matriz esta al 0% -->
                                             {% else %}
                                                 <input class="button_active ejes_diagonal_gris" type="text" value="0" title="Sin influencia">
                                             {% endif %}
                                        {% else %}
                                             <!-- diagonal de la matriz-->
                                             {% if celda.y == celda.x and celda.x != ''  %}
                                                 <input class="button_active ejes_diagonal_gris" type="text" value="0" title="Sin influencia">
                                             <!-- sumatorias de filas y columnas -->
                                             {% elif celda.x == '' %}
                                                <input class="button_active" type="text" value="{{celda.valor}}" title="{{celda.descripcion}}">
                                             <!-- influencias directas -->
                                             {% else %}
                                                 <input class="button_active"
                                                        {% if consenso is False and estudio.estado %}
                                                            onclick="location.href='{% url 'mactor:editar_mid' celda.pk 'matriz' %}'"
                                                        {% elif estudio.estado is False and consenso is False %}
                                                            onclick="location.href='{% url 'mactor:consultar_mid' celda.pk 'matriz' %}'"
                                                        {% elif consenso %}
                                                            onclick="location.href='{% url 'mactor:consultar_mid' celda.pk 'consenso' %}'"
                                                        {% endif %}
                                                        type="text" value="{{celda.valor}}" title="{{celda.descripcion}}">
                                             {% endif %}
                                        {% endif %}
                                    {% endif %}
                                </tr>
                            {% endfor %}
                            <br>
                        {% endfor %}
                    {% else %}
                        <h3>No se han registrado actores en el estudio.</h3>
                    {% endif %}
                  </tbody>
              </table>
            <br>
            {% if consenso %}
                <div class="alert alert-info alert-dismissible">
                     <br>
                     <h4>Expertos en consenso = {{expertos}}</h4>
                </div>
            {% endif %}
            <br>


            <!--BOTONES ------------------------------- -->

                <div class="form-group">
                    <div class="col-md-offset-2 col-md-8">
                        <a class="btn btn-success" href="{% url 'mactor:influenciasMID' estudio.id %}" title="Influencias directas"><i class="fa fa-arrow-left"></i> Atrás</a>
                        <a class="btn btn-primary" data-toggle="modal" href="#modalAyuda" title="Ayuda"><i class="fa fa-book"></i> Ayuda</a>
                    </div>
                </div>

            <!--MODAL CONSULTAR ACTOR--------------- -->

            {% include 'mactor/actor/modal_detalle_actor.html' %}

             <!--MODAL ESTADO DEL ESTUDIO------------ -->

            {% include 'mactor/mid/matrices/modal_estado_estudio.html' %}

             <!--MODAL AYUDA------------------------- -->

		    <div id="modalAyuda" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
				  <div class="modal-dialog">
					  <div class="modal-content">
						  <div class="modal-header">
							  <button type="button" class="close" data-dismiss="modal" aria-hidden="true">X</button>
							  <h4 class="modal-title">Ayuda - Influencias directas</h4>
						  </div>
						  <div class="modal-body" style="text-align: justify">
							 <p>La Matriz de Influencias Directas (MID), permite evidenciar el nivel de influencia
                                que un actor ejerce sobre otro de forma directa, asi: el actor tiene poca o ninguna
                                influencia sobre otro (0), el actor puede poner en riesgo de forma limitada los
                                procesos operativos de gestión de otro (1), el actor puede poner en riesgo el éxito
                                de los proyectos de otro actor (2), el actor puede poner en riesgo el cumplimiento
                                de las misiones de otro actor (3) y por último el actor puede poner en riesgo la
                                existencia o permanencia de otro (4) (Godet y Durance, 2009).
                            </p>
                            <p>La columna Influencia Directa (Inf. D), representa la influencia que determinado
                                actor ejerce en el grupo de actores estudiado. Mientras que la fila Dependencia
                                Directa (Dep. D), la influencia que el mismo actor recibe del resto de actores.
                            </p>
						  </div>
						  <div class="modal-footer">
							  <button type="button" class="btn btn-default" data-dismiss="modal" aria-hidden="true">Cerrar</button>
						  </div>
					  </div>
				  </div>
			  </div>

            </div>
            <!-- /.box-body -->
          </div>
        {% endif %}
    {% else %}
        <h2>No cuenta con permisos para acceder a esta página.</h2>
    {% endif %}

{% endblock %}

{% block extra_js %}
    <script src="{% static 'js/mactor/consultar_actor_objetivo_matriz.js'%}"></script>
    <script>
        $('input').attr('readonly', true);
    </script>
{% endblock %}

templates/mactor/mid/matrices/modal_acceso_matrices.html
<!-- Modal de acceso a matrices de mid -->
<div id="modalMatrices" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">X</button>
                <h4 class="modal-title">Matrices de Análisis de los actores</h4>
            </div>
            <div class="modal-body" style="text-align: center">
                <a class="btn btn-primary botones_modal" href="{% url 'mactor:matriz_mid' estudio.id %}">MID - Matriz de Influencias Directas</a>
                {% if porcentaje == 100 %}
                    <a class="btn btn-primary botones_modal" href="{% url 'mactor:matriz_midi' estudio.id %}">MIDI - Matriz de Influencias Directas e Indirectas</a>
                    <a class="btn btn-primary botones_modal" href="{% url 'mactor:matriz_maxima' estudio.id %}">MAX - Matriz de Máxima Influencia Directa e Indirecta</a>
                    <a class="btn btn-primary botones_modal" href="{% url 'mactor:matriz_balance' estudio.id %}">BL - Matriz de Balance Líquido</a>
                    <a class="btn btn-primary botones_modal" href="{% url 'mactor:matriz_ri' estudio.id %}">Ri-Qi - Coeficientes de Fuerza de los actores</a>
                {% else %}
                    <a class="btn btn-primary botones_modal" disabled="True" title="Finalice la matriz MID para acceder a MIDI">MIDI - Matriz de Influencias Directas e Indirectas</a>
                    <a class="btn btn-primary botones_modal" disabled="True" title="Finalice la matriz MID para acceder a MAX">MAX - Matriz de Máxima Influencia Directa e Indirecta</a>
                    <a class="btn btn-primary botones_modal" disabled="True" title="Finalice la matriz MID para acceder a BL">BL - Matriz de Balance Líquido</a>
                    <a class="btn btn-primary botones_modal" disabled="True" title="Finalice la matriz MID para acceder a Ri - Qi">Ri-Qi - Coeficientes de Fuerza de los actores</a>
                {% endif %}

            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal" aria-hidden="true">Cerrar</button>
            </div>
        </div>
    </div>
</div>


<!-- Modal de acceso a matrices consenso de mid -->
<div id="modalMatricesConsenso" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">X</button>
                <h4 class="modal-title">Consenso Matrices de Análisis de los actores</h4>
            </div>
            <div class="modal-body" style="text-align: center">
                <a class="btn btn-success botones_modal" href="{% url 'mactor:consenso_mid' estudio.id 1 %}">MID - Matriz de Influencias Directas</a>
                <a class="btn btn-success botones_modal" href="{% url 'mactor:consenso_mid' estudio.id 2 %}">MIDI - Matriz de Influencias Directas e Indirectas</a>
                <a class="btn btn-success botones_modal" href="{% url 'mactor:consenso_mid' estudio.id 3 %}">MAX - Matriz de Máxima Influencia Directa e Indirecta</a>
                <a class="btn btn-success botones_modal" href="{% url 'mactor:consenso_mid' estudio.id 4 %}">BL - Matriz de Balance Líquido</a>
                <a class="btn btn-success botones_modal" href="{% url 'mactor:consenso_mid' estudio.id 5 %}">Ri-Qi - Coeficientes de Fuerza de los actores</a>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal" aria-hidden="true">Cerrar</button>
            </div>
        </div>
    </div>
</div>

templates/mactor/mid/matrices/opciones_midi.html
<div class="pull-right">
    {% if matriz and actores %}
        <select name="graficos_midi" class="form-control" onchange="location = this.value;">
            <option value="">Análisis MIDI</option>
            {% if consenso %}
                <option value="{% url 'mactor:consenso_mid' estudio.id 8 %}">Mapa de actores</option>
                <option value="{% url 'mactor:consenso_mid' estudio.id 6 %}">Coeficiente de estabilidad H</option>
            {% else %}
                <option value="{% url 'mactor:mapa_actores' estudio.id %}">Mapa de actores</option>
                <option value="{% url 'mactor:estabilidad' estudio.id %}">Coeficiente de estabilidad H</option>
            {% endif %}
        </select>
    {% endif %}
</div>