apps/entrevista/urls.py
from django.conf.urls import url
from django.contrib.auth.decorators import login_required
from .views import CrearEstudio, EditarEstudio, ConsultarEstudio, EliminarEstudio, \
    ListaPreguntas, CrearPregunta, EditarPregunta, ConsultarPregunta, EliminarPregunta,\
    ListaValoresEscala, CrearValorEscala, EditarValorEscala, ConsultarValorEscala, EliminarValorEscala, \
    ListaRondas, CrearRonda, EditarRonda, ConsultarRonda, \
    ListaJuicios, CrearJuicio, ConsultarJuicio, EditarJuicio, MatrizJuicios, \
    ListaCoeficientes, GraficoCoeficiente, datos_grafico, exportar_estudio_xls, cambiar_estado_pregunta_escala_ronda

urlpatterns = [

    # Urls modelo Estudio_entrevista
    url(r'^agregar_estudio/(?P<pk>\d+)/$', CrearEstudio.as_view(), name='nuevo_estudio'),
    url(r'^editar_estudio/(?P<pk>\d+)/$', login_required(EditarEstudio.as_view()), name='editar_estudio'),
    url(r'^consultar_estudio/(?P<pk>\d+)/$', login_required(ConsultarEstudio.as_view()), name='consultar_estudio'),
    url(r'^eliminar_estudio/(?P<pk>\d+)/$', login_required(EliminarEstudio.as_view()), name='eliminar_estudio'),


    # Urls modelo Pregunta
    url(r'^lista_preguntas/(\d+)/$', login_required(ListaPreguntas.as_view()), name='preguntas'),
    url(r'^nueva_pregunta/(\d+)/$', login_required(CrearPregunta.as_view()), name='nueva_pregunta'),
    url(r'^editar_pregunta/(?P<pk>\d+)/$', login_required(EditarPregunta.as_view()), name='editar_pregunta'),
    url(r'^consultar_pregunta/(?P<pk>\d+)/$', login_required(ConsultarPregunta.as_view()), name='consultar_pregunta'),
    url(r'^eliminar_pregunta/(?P<pk>\d+)/$', login_required(EliminarPregunta.as_view()), name='eliminar_pregunta'),

    # Urls modelo Valor escala
    url(r'^escala_likert/(\d+)/$', login_required(ListaValoresEscala.as_view()), name='escala'),
    url(r'^nuevo_valor/(\d+)$', login_required(CrearValorEscala.as_view()), name='nuevo_valor'),
    url(r'^editar_valor/(?P<pk>\d+)/$', login_required(EditarValorEscala.as_view()), name='editar_valor'),
    url(r'^consultar_valor/(?P<pk>\d+)/$', login_required(ConsultarValorEscala.as_view()), name='consultar_valor'),
    url(r'^eliminar_valor/(?P<pk>\d+)/$', login_required(EliminarValorEscala.as_view()), name='eliminar_valor'),

    # Urls modelo Ronda Juicio
    url(r'^lista_rondas/(\d+)/$', login_required(ListaRondas.as_view()), name='rondas'),
    url(r'^registrar_ronda/(\d+)/$', login_required(CrearRonda.as_view()), name='nueva_ronda'),
    url(r'^editar_ronda/(?P<pk>\d+)/$', login_required(EditarRonda.as_view()), name='editar_ronda'),
    url(r'^consultar_ronda/(?P<pk>\d+)/$', login_required(ConsultarRonda.as_view()), name='consultar_ronda'),

    # Urls modelo Juicio
    url(r'^lista_juicios/(\d+)/$', login_required(ListaJuicios.as_view()), name='juicios'),
    url(r'^registrar_juicio/(\d+)/$', login_required(CrearJuicio.as_view()), name='nuevo_juicio'),
    url(r'^consultar_juicio/(?P<pk>\d+)/(?P<tipoAcceso>\w+)/$', login_required(ConsultarJuicio.as_view()),
        name='consultar_juicio'),
    url(r'^editar_juicio/(?P<pk>\d+)/$', login_required(EditarJuicio.as_view()), name='editar_juicio'),
    url(r'^matriz_juicios/(\d+)/$', login_required(MatrizJuicios.as_view()), name='matriz_juicios'),

    # Urls modelo coeficiente
    url(r'^historial_coeficientes/(\d+)/$', login_required(ListaCoeficientes.as_view()), name='historial_coeficientes'),
    url(r'^grafico_coeficiente/(\d+)/$', login_required(GraficoCoeficiente.as_view()), name='grafico'),
    url(r'datos_grafico_coef', login_required(datos_grafico)),

    # Urls exportar a excel
    url(r'exportar_estudio/xls/(?P<idEstudio>\d+)/$', login_required(exportar_estudio_xls), name='exportar_excel'),

    # cambiar por ajax el estado de una pregunta, opcion de la escala o ronda (solo si esta abierta)
    url(r'cambiar_estado', login_required(cambiar_estado_pregunta_escala_ronda)),

]

apps/proyecto/urls.py
from django.conf.urls import url
from django.contrib.auth.decorators import login_required
from .views import Listaproyectos, CrearProyecto, ConsultarProyecto, \
  EditarProyecto, EliminarProyecto, \
  ConsultarEstudiosProyecto, \
  EnviarMensaje, ConsultarMensaje, obtener_destinatarios, \
  cambiar_estado_mensaje, \
  EnviarMensajeEstudio, ConsultarMensajeEstudio, obtener_destinatarios_estudios

urlpatterns = [

  url(r'^proyectos_prospectivos', login_required(Listaproyectos.as_view()),
      name='proyectos_prospectivos'),
  url(r'^agregar_proyecto/$', login_required(CrearProyecto.as_view()),
      name='nuevo_proyecto'),
  url(r'^detalle_proyecto/(?P<pk>\d+)/$',
      login_required(ConsultarProyecto.as_view()), name='ver_proyecto'),
  url(r'^estudios_proyecto/(?P<pk>\d+)/$',
      login_required(ConsultarEstudiosProyecto.as_view()),
      name='ver_estudios_proyecto'),
  url(r'^editar_proyecto/(?P<pk>\d+)/$',
      login_required(EditarProyecto.as_view()), name='editar_proyecto'),
  url(r'^eliminar_proyecto/(?P<pk>\d+)/$',
      login_required(EliminarProyecto.as_view()), name='eliminar_proyecto'),

  # urls de mensajes
  url(r'obtener_destinatarios', login_required(obtener_destinatarios)),
  url(r'^mensajes_proyecto/(?P<pk>\d+)/$',
      login_required(EnviarMensaje.as_view()), name='mensajes'),
  url(r'^ver_mensaje/(?P<pk>\d+)/$', login_required(ConsultarMensaje.as_view()),
      name='ver_mensaje'),

  url(r'destinatarios_estudios',
      login_required(obtener_destinatarios_estudios)),
  url(r'^mensajes_estudios/(?P<pk>\d+)/(?P<tipoEstudio>\d+)/$',
      login_required(EnviarMensajeEstudio.as_view()), name='mensajes_estudio'),
  url(r'^ver_mensaje_estudio/(?P<pk>\d+)/$',
      login_required(ConsultarMensajeEstudio.as_view()),
      name='ver_mensaje_estudio'),
  url(r'cambiar_estado_mensaje', login_required(cambiar_estado_mensaje)),

]

apps/usuario/urls.py
from django.conf.urls import url
from django.contrib.auth.decorators import login_required
from .views import RegistrarUsuarioProyecto, RegistrarUsuarioEstudio

urlpatterns = [
    # si id = 0, se esta agregando un usuario desde la vista de creacion
    # si id != 0 se esta agregando un usuario desde la vista de edicion
    url(r'^registrar_usuario_proyecto/(?P<id>\d+)/$', login_required(RegistrarUsuarioProyecto.as_view()), name='registrar_usuario_proyecto'),
    url(r'^registrar_usuario_estudio/(?P<idProyecto>\d+)/(?P<tipoEstudio>\d+)/(?P<idEstudio>\d+)/$', login_required(RegistrarUsuarioEstudio.as_view()), name='registrar_usuario_estudio'),
    ]

softprosp/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from apps.usuario.views import UserRegistrationView

urlpatterns = [
  url(r'^admin/', admin.site.urls),
  # sobreescritura del formulario de registro de registration-redux
  url(r'^accounts/register/$', UserRegistrationView.as_view(),
      name='registration_register'),
  url(r'^proyecto/', include('apps.proyecto.urls', namespace="proyecto")),
  url(r'^usuario/', include('apps.usuario.urls', namespace="usuario")),
  url(r'^abaco/', include('apps.abaco.urls', namespace="abaco")),
  url(r'^delphi/', include('apps.delphi.urls', namespace="delphi")),
  url(r'^entrevista/', include('apps.entrevista.urls', namespace="entrevista")),
  url(r'^brainstorming/',
      include('apps.brainstorming.urls', namespace="brainstorming")),
  url(r'^mactor/', include('apps.mactor.urls', namespace="mactor")),
  url(r'^multipol/', include('apps.multipolv1.urls', namespace='multipol')),
  url(r'^extrapolacion', include('apps.extrapolacion_tendencias.urls',
                                 namespace='extrapolacion')),
  # urls vista control de usuarios paquete Registration redux
  url(r'^accounts/', include('registration.backends.default.urls')),
]

apps/entrevista/models.py
from django.db import models
from ..proyecto.models import Proyecto, Tecnica
from django.contrib.auth.models import User
from django.utils.timezone import now
from django.core.urlresolvers import reverse

"""MODELO ESTUDIO ENTREVISTA---------------------------------------------------------------------------------"""


class EstudioEntrevista(models.Model):

    tipoTecnica = models.ForeignKey(Tecnica, null=True)  # el tipo se agrega mandando e objeto por contexto
    titulo = models.CharField(max_length=200)
    objetivo = models.TextField()
    entrevistador = models.CharField(max_length=50, null=True, blank=True)
    entrevistado = models.CharField(max_length=50)
    idAdministrador = models.ForeignKey(User, verbose_name='Administrador', related_name='ent_administrador')
    idCoordinador = models.ForeignKey(User, verbose_name='Coordinador', related_name='ent_coordinador')
    idExpertos = models.ManyToManyField(User, verbose_name='Expertos', related_name='ent_expertos_set')
    fecha_inicio = models.DateField(default=now)
    fecha_final = models.DateField(default=now)
    estado = models.BooleanField(default=True)
    idProyecto = models.ForeignKey(Proyecto, null=True, on_delete=models.CASCADE)

    class Meta:
        verbose_name = 'Estudio entrevista'
        verbose_name_plural = 'Estudios entrevista'
        unique_together = [('titulo', 'tipoTecnica', 'idProyecto')]

    def get_absolute_url(self):
        return reverse('proyecto:ver_estudios_proyecto', args={self.idProyecto.id})

    def __str__(self):
        return u'{0}'.format(self.titulo)

"""MODELO PREGUNTA-------------------------------------------------------------------------------------------"""


class Pregunta(models.Model):

    texto_pregunta = models.TextField()
    texto_respuesta = models.TextField(null=True, blank=True)
    observacion = models.TextField(null=True, blank=True)
    estado = models.BooleanField(default=True)
    idEstudio = models.ForeignKey(EstudioEntrevista, default=0, on_delete=models.CASCADE)

    class Meta:
        verbose_name = 'Pregunta'
        verbose_name_plural = 'Preguntas'
        unique_together = ('texto_pregunta', 'idEstudio')

    def get_absolute_url(self):
        return reverse('entrevista:preguntas', args={self.idEstudio.id})

    def __str__(self):
        return u'{0}'.format(self.texto_pregunta)


"""MODELO VALOR ESCALA LIKERT----------------------------------------------------------------------------------"""


class ValorEscalaLikert(models.Model):

    nombre = models.TextField()
    valor = models.IntegerField()
    estado = models.BooleanField(default=True)
    descripcion = models.TextField(null=True, blank=True)
    idEstudio = models.ForeignKey(EstudioEntrevista, default=0, on_delete=models.CASCADE)

    class Meta:
        verbose_name = 'Escala de Likert'
        verbose_name_plural = 'Escala de Likert'
        unique_together = [('nombre', 'valor', 'estado', 'idEstudio')]

    def get_absolute_url(self):
        return reverse('entrevista:escala', args={self.idEstudio.id})

    def __str__(self):
        return u'{0}'.format(self.nombre)


"""MODELO RONDA JUICIO---------------------------------------------------------------------------------------"""


class RondaJuicio(models.Model):

    numero_ronda = models.IntegerField()
    descripcion = models.TextField(null=True, blank=True)
    fecha_inicio = models.DateField(default=now)
    fecha_final = models.DateField()
    estado = models.BooleanField(default=True)
    numero_preguntas = models.IntegerField(default=1)
    idEstudio = models.ForeignKey(EstudioEntrevista, default=0, on_delete=models.CASCADE)

    class Meta:
        verbose_name = 'Ronda de juicio'
        verbose_name_plural = 'Rondas de juicio'
        unique_together = ('numero_ronda', 'idEstudio')

    def get_absolute_url(self):
        return reverse('entrevista:rondas', args={self.idEstudio.id})

    def __str__(self):
        return u'{0} - {1}'.format(self.numero_ronda, self.idEstudio)


"""MODELO JUICIO DE EXPERTOS----------------------------------------------------------------------------------------"""


class Juicio(models.Model):

    texto_pregunta = models.TextField()
    idValorEscala = models.ForeignKey(ValorEscalaLikert, default=0, on_delete=models.CASCADE)
    justificacion = models.TextField(null=True, blank=True)
    idExperto = models.ForeignKey(User, null=True)
    idRonda = models.ForeignKey(RondaJuicio, default=0, on_delete=models.CASCADE)

    class Meta:
        verbose_name = 'Juicio de expertos'
        verbose_name_plural = 'Juicios de los expertos'
        unique_together = ('texto_pregunta', 'idExperto', 'idRonda')

    def __str__(self):
        return u'{0} - {1} - {2}'.format(self.texto_pregunta, self.idValorEscala, self.idRonda)


"""MODELO COEFICIENTE ALFA DE CRONBACH------------------------------------------------------------------------------"""


class CoeficienteAlfa(models.Model):

    valor = models.FloatField()
    idRonda = models.ForeignKey(RondaJuicio, default=0, on_delete=models.CASCADE)
    num_expertos = models.IntegerField()

    class Meta:
        verbose_name = 'Coeficiente Alfa de Cronbach'
        verbose_name_plural = 'Coeficiente Alfa de Cronbach'

    def __str__(self):
        return u'{0} - {1} - {2}'.format(self.idRonda, self.valor, self.num_expertos)


# Sobreescritura del modelo usuario


def get_name(self):
    if self.first_name != '':
        return '{} {}'.format(self.first_name, self.last_name)
    else:
        return '{}'.format(self.username)

User.add_to_class("__str__", get_name)

templates/entrevista/estudio/crear_estudio_entrevista.html
{% extends 'base.html' %}
{% load staticfiles %}
{% load crispy_forms_tags %}

{% block extra_css %}
    <!-- Select2 -->
    <link rel="stylesheet" href="{% static 'css/select2/css/select2.min.css' %}">
    <!-- DataPicker -->
    <link rel="stylesheet" href="{% static 'css/bootstrap-datepicker.min.css' %}">

    <style>
        #expertos li { color: black }
    </style>
{% endblock %}

{% block content %}
    {% if request.user == proyecto.idAdministrador and proyecto.estado %}
        <div class="matter">
            <div class="container">
                <div class="row">
                    <div class="col-md-12">
                            <div class="widget-head">
                                <div class="box-header with-border">
                                  <h3 class="box-title">Nuevo estudio Entrevista</h3>
                                </div>
                            </div>
                            <div class="widget-content">
                                <div class="padd">
										<hr/>

                                    {% include 'messages.html' %}

										<!-- Form starts.  -->
                                    <form class="form-horizontal" role="form" method="post">
                                        {% csrf_token %}

                                       <div class="row hidden">
                                            <div class="col-md-8 col-md-offset-1">
                                                <label class="control-label" style="text-align: left">Tecnica</label>
                                                <input class="form-control" type="text" value="{{tecnica}}" name="tipoTecnica">
                                            </div>
                                        </div>

                                        <div class="row">
                                            <div class="col-md-8 col-md-offset-1">
                                                {{ form.titulo|as_crispy_field }}
                                            </div>
                                        </div>

                                        <div class="row">
                                            <div class="col-md-8 col-md-offset-1">
                                                {{ form.objetivo|as_crispy_field }}
                                            </div>
                                        </div>

                                        <div class="row">
                                            <div class="col-md-8 col-md-offset-1">
                                                {{form.entrevistador|as_crispy_field}}
                                            </div>
                                        </div>

                                        <div class="row">
                                            <div class="col-md-8 col-md-offset-1">
                                                {{form.entrevistado|as_crispy_field}}
                                            </div>
                                        </div>

                                        <div  class="row">
                                            <div class="col-md-3 col-md-offset-1" hidden>
                                                <label class="control-label" style="text-align: left">Administrador</label>
                                                <input class="form-control" type="text" value="{{proyecto.idAdministrador_id}}" name="idAdministrador">
                                            </div>
                                        </div>

                                        <div class="row">
                                            <div class="col-md-8 col-md-offset-1">
                                                <div class="form-group">
                                                    <label class="control-label" style="text-align: left">Coordinador*</label>
                                                    <select name="idCoordinador" class="form-control select2" required id="id_idCoordinador">
                                                        <option value="" selected>----Seleccionar----</option>
                                                        {% for coo in proyecto.idCoordinadores.all %}
                                                            <option value="{{coo.id}}">{{coo}}</option>
                                                        {% endfor %}
                                                    </select>
                                                </div>
                                            </div>
                                        </div>

                                        <div class="row" id="expertos">
                                            <div class="col-md-8 col-md-offset-1">
                                                {{form.idExpertos|as_crispy_field}}
                                            </div>
                                        </div>

                                        <div class="row">
                                            <div class="col-md-8 col-md-offset-1">
                                                {{form.fecha_inicio|as_crispy_field}}
                                            </div>

                                            <div class="col-md-8 col-md-offset-1">
                                                <span style="color: red">Nota: Tenga en cuenta que la fecha final no puede ser posterior a la fecha de cierre del proyecto ({{ proyecto.fecha_final }}). </span>
                                                <br>
                                                {{form.fecha_final|as_crispy_field}}
                                            </div>
                                        </div>

                                        <div class="row">
                                           <div class="col-md-8 col-md-offset-1">
                                               <span style="color: red">Nota: Al cumplirse la fecha de cierre del estudio, el estado de este cambiará automáticamente a cerrado. </span>
                                               <br>
                                               {{ form.estado|as_crispy_field }}
                                            </div>

                                            <div class="col-md-8 col-md-offset-1 hidden">
                                                <label class="control-label" style="text-align: left">Proyecto</label>
                                                <input class="form-control" type="text" value="{{proyecto.id}}" name="idProyecto">
                                            </div>
                                        </div>

                                        <br>
                                        <div class="form-group">
                                            <div class="col-md-8 col-md-offset-3">
                                                <a class="btn btn-success" href="{% url 'proyecto:ver_estudios_proyecto' proyecto.id %}" title="Estudios del proyecto"><i class="fa fa-arrow-left"></i> Atrás</a>
                                                <a class="btn btn-primary" href="{% url 'usuario:registrar_usuario_estudio' proyecto.id 2 0 %}" title="Registrar nuevo usuario"><i class="fa fa-plus"></i> Usuario</a>
                                                <a class="btn btn-primary" data-toggle="modal" href="#myModal" title="Ayuda"><i class="fa fa-book"></i> Ayuda</a>
                                                <button type="submit" class="btn btn-primary" title="Guardar"><i class="fa fa-save"></i> Guardar</button>
                                            </div>
                                        </div>
                                    </form>

                                </div>
                            </div>

        <!--INICIO MODAL AYUDA------------------------- -->

		<div id="myModal" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
				  <div class="modal-dialog">
					  <div class="modal-content">
						  <div class="modal-header">
							  <button type="button" class="close" data-dismiss="modal" aria-hidden="true">X</button>
							  <h4 class="modal-title">Ayuda - Nuevo estudio MACTOR</h4>
						  </div>
						  <div class="modal-body" style="text-align: justify">
							  <p>Ingrese la información básica del estudio, tenga en cuenta los roles que pueden ser ejercidos
                                  dentro del mismo:
								  <br>
								  <br>
								  <i class="fa fa-user"></i> Administrador: encargado de crear y finalizar el estudio. También
                                  puede llevar a cabo las tareas del coordinador.
								  <br>
								  <br>
								  <i class="fa fa-user"></i> Coordinador: responsable de registrar las entradas necesarias
                                  para el desarrollo del estudio (actores, estrategias y objetivos) y redactar el informe final
                                  de acuerdo al consenso entre los expertos.
								  <br>
								  <br>
								  <i class="fa fa-users"></i> Experto: encargado de diligenciar las matrices necesarias para
                                el análisis de las convergencias y divergencias entre los actores respecto a los objetivos
                                estudiados.
								  <br>
								  <br>
								  <p style="color: black">Nota 1: El administrador puede ocupar dentro de un estudio los tres roles descritos, asi como
                                el coordinador designado puede hacer parte del grupo de expertos.</p>
                                <p style="color: black">Nota 2: Una vez finalizado el estudio el coordinador cuenta con la cantidad de dias registrados al
                                    crear el estudio para redactar el informe, este informe puede ser modificado siempre que el estado del
                                    mismo sea "Abierto". Usted como administrador cuenta con el permiso de redactar, modificar y cerrar el informe
                                    si asi lo desea. </p>

							  </p>
						  </div>
						  <div class="modal-footer">
							  <button type="button" class="btn btn-default" data-dismiss="modal" aria-hidden="true">Cerrar</button>
						  </div>
					  </div>
				  </div>
			  </div>

                    </div>
                </div>
            </div>
</div>
    {% else %}
        <h2>No cuenta con permisos para acceder a esta página.</h2>
    {% endif %}

{% endblock %}

{% block extra_js %}
    <!-- Select2 -->
    <script src="{% static 'js/select2/js/select2.full.min.js' %}"></script>
    <!-- Datapicker -->
    <script src="{% static 'js/moment.min.js' %}"></script>
    <script src="{% static 'js/bootstrap-datepicker.min.js' %}"></script>
    <script src="{% static 'js/entrevista/controlFechas.js' %}"></script>

     <script>
        $(function ()
        {
            //Initialize Select2 Elements
            $('.select2').select2()
        })
    </script>
{% endblock %}

templates/entrevista/estudio/eliminar_estudio_entrevista.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block content %}
    {% if estudio.idAdministrador == request.user %}
        <div class="matter">
            <div class="container">
                <div class="row">
                    <div class="col-md-12">
                            <div class="widget-head">
                                <div class="box-header with-border">
                                  <h3 class="box-title">Eliminar Estudio - Entrevista</h3>
                                </div>
                            </div>
                            <div class="widget-content">
                                <div class="padd">
										<hr/>
										<!-- Form starts.  -->
                                    <form class="form-horizontal" role="form" method="post">
                                        {% csrf_token %}

                                        <div class="jumbotron row col-md-10 col-md-offset-1">
                                            <h3>¿Desea eliminar el estudio: {{ estudio.titulo }}?</h3>
                                        </div>

                                        <div class="form-group">
                                            <div class="col-md-8 col-md-offset-3">
                                                <a class="btn btn-success" href="{% url 'proyecto:ver_estudios_proyecto' estudio.idProyecto_id %}"><i class="fa fa-arrow-left"></i> Cancelar</a>
                                                <button type="submit" class="btn btn-danger" title="Eliminar"><i class="fa fa-trash"></i> Si, eliminar</button>
                                            </div>
                                        </div>
                                    </form>

                                </div>
                            </div>
                    </div>
                </div>
            </div>
</div>
    {% else %}
        <h2>No cuenta con permisos para acceder a esta página.</h2>
    {% endif %}

{% endblock %}

templates/entrevista/estudio/select_datos_estudio.html
<!--Opciones que dan acceso a los diferentes datos del estudio mactor-->

<select style="float: right" onchange="location = this.value;">
    <option value="">Opciones</option>
    <option value="{% url 'proyecto:ver_estudios_proyecto' estudio.idProyecto_id %}">Estudios del proyecto</option>
    <option value="{% url 'proyecto:ver_proyecto' estudio.idProyecto_id %}">Detalle del proyecto</option>
    <option value="{% url 'entrevista:consultar_estudio' estudio.id %}">Detalle del estudio</option>
    {% if usuario == 'COORDINADOR' %}
        <option value="{% url 'entrevista:preguntas' estudio.id %}">Cuestionario</option>
        <option value="{% url 'entrevista:escala' estudio.id %}">Escala de Likert</option>
    {% endif %}
    <option value="{% url 'entrevista:rondas' estudio.id %}">Rondas de juicio</option>
    <option value="{% url 'entrevista:juicios' estudio.id %}">Juicios</option>
    {% if usuario == 'COORDINADOR' %}
        <option value="{% url 'entrevista:historial_coeficientes' estudio.id %}">Coeficientes Alpha</option>
    {% endif %}
    <option value="{% url 'entrevista:exportar_excel' estudio.id %}">Descargar datos</option>
</select>